### ISSUE TITLE
Augment Closed reasons

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#102]
I'd like to add some custom closed reason such as: 

```
PCL Question: The PCL community prefers to answer questions at http://www.pcl-developers.org/
OpenCV Question: THe OpenCV community prefers to answer questions at: http://answers.opencv.org/questions/
MoveIt Question: The MoveIt! community prefers to answer questions at: https://groups.google.com/forum/#!forum/moveit-users/join
```

@evgenyfadeev Is modifying CLOSE_REASONS the right way to do this? https://github.com/ASKBOT/askbot-devel/blob/master/askbot/const/__init__.py#L11 is there anything else needed?

**Comment by taketwo** [comment]
PCL community would rather prefer to answer questions at http://www.pcl-users.org/. The other list is for communications between PCL developers.

**Comment by tfoote** [comment]
Thanks @taketwo we'll use that.

**Comment by evgenyfadeev** [comment]
Applied as a hotfix on your instance, will implement editing of the close reasons later.
