### ISSUE TITLE
moderation: clicking 'flagged items' results in "Page not found"

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#103]
I may not have enough rights, but every now and then I get a _flagged items (N)_ link in my Inbox. Clicking it always takes me to a "Sorry, could not find the page you requested." page.

URL it tries to open: http://answers.ros.org/users/NNNN/USER/?sort=inbox&section=flags

**Comment by evgenyfadeev** [comment]
The url to the moderation queue is  http://answers.ros.org/moderation-queue/

Is the "old style" (as in the bug report above) link still shown somewhere? Could you please reopen or comment again if that's so?

**Comment by gavanderhoorn** [comment]
I'll have to wait until I have posts to moderate. Only then did the link show up.

**Comment by gavanderhoorn** [comment]
@evgenyfadeev: current inbox shows a _flagged items_ link, target is exactly the same as in the OP.

It's on the _Inbox_ page of my user profile. I get a `Sections: forum responses (8) | flagged items (5)` right underneath the `overview | inbox | ..` nav bar.

**Comment by gavanderhoorn** [comment]
I'd like this to be reopened, as I just ran into this again.

![ros answers flagged items](https://cloud.githubusercontent.com/assets/4550046/7460271/07bc889c-f2a2-11e4-9a2b-fb868be2ea40.png)

Clicking on the _flagged items (2)_ link leads me to:

![ros answers flagged items page not found](https://cloud.githubusercontent.com/assets/4550046/7460278/100a2cb6-f2a2-11e4-8db7-68eb62539402.png)

Clicking on the warning sign (next to my account name) does take me to the moderation queue.
