### ISSUE TITLE
get-tag-list page includes spam tags

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#104]
Seems the [get-tag-list](http://answers.ros.org/get-tag-list/) page includes the tags added by spam posts:

```
9680801434
love
ØªÙˆÙƒÙŠÙ„
astrology
[..]
vashikaran
[..]
9001354274
[..]
ØµÙŠØ§Ù†Ø©
[..]
specialist
[..]
black
[..]
magic
mantra
[..]
```

**Comment by evgenyfadeev** [comment]
Unfortunately those tags that accumulated will need to be deleted manually.
The spam posts often use legitimate tags as well, so they can't be deleted at all once.

I will try to identify the obvious ones tomorrow, but other than that, please report the tags that you think should be deleted and I'll clear them out. (I've deleted the ascii tags above, the two with strange characters I haven't found yet).

Deletion of newly created spam tags should be implemented in the moderation queue.

**Comment by gavanderhoorn** [comment]
@evgenyfadeev wrote:

> Unfortunately those tags that accumulated will need to be deleted manually.
> The spam posts often use legitimate tags as well, so they can't be deleted at all once.

Tags aren't 'reference counted'? Would it be an option to delete all tags that are in _difference(tags_on_other_posts, tags_on_spam_posts)_?

**Comment by evgenyfadeev** [comment]
@gavanderhoorn this might work, thank you for the idea, will try to get this done.

**Comment by tfoote** [comment]
Also in the list of tags with count. 

If we can suppress the output that's fine. keeping them in the database is incidental.

**Comment by gavanderhoorn** [comment]
I'm getting a 404 on the `get-tag-list` page now, so this is probably no longer relevant.
