### ISSUE TITLE
the search feed sorted by activity does not show the latest updates

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#105]
About 9 hours ago (~2pm PST) is the last reported activity on the main view sorted by activity. 

I made a comment and updated a question. The content saved, but it doesn't show as newer on the activity sorting.

**Comment by tfoote** [comment]
Hmm, maybe it was just a slow afternoon. i had only tested with a comment. editing the question updated the activity timestamp. And a different new question came in.

**Comment by evgenyfadeev** [comment]
some things are executed asynchronously, for example, the view counts on the main page are updated that way. If the queue is overwhelmed some data as shown will be outdated until the queue cleared.

I've restarted the application process and will now wait till the memory usage equilibrates, then will see how many queue processes can be added to reduce the chance of this lag.
