### ISSUE TITLE
answers with most upvotes is at the bottom

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#106]
On this question, the answer with the most upvotes (mine) appears at the bottom of the page, instead of the top: http://answers.ros.org/question/187851/problem-during-compilation-of-ros-indigo-on-armubuntu-trusty-from-source/

A quick sampling of other questions from the front page suggests that this is not limited to this question: http://answers.ros.org/question/110516/rgbdslam-freiburg-hydro/
http://answers.ros.org/question/174374/ros-indigo-turtlebot-gazebo-simulation/
http://answers.ros.org/question/50763/need-help-converting-lat-long-coordinates-into-meters/
http://answers.ros.org/question/197868/can-a-node-be-a-subscriber-and-client-at-the-same-time/

**Comment by evgenyfadeev** [comment]
This is due to the setting answer sort order "sort answers by date".
Someone must have changed it. The default is by the number of votes.

I.e. to close this issue either the current behavior must be accepted or setting changed to sorting by the number of votes.

**Comment by tfoote** [comment]
That's odd. I changed the setting back to be by votes.
