### ISSUE TITLE
Timestamp is messed up

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#108]
For example, timestamp in the OP of http://answers.ros.org/question/200153/roslaunch-does-not-work-but-rusrun-does/ does not make sense as follows:
- Asked 15 hrs ago
- Updated 26 hrs ago

**Comment by tfoote** [comment]
Are you sure it was hours? I see it now saying minutes for the time since update.
![screenshot from 2014-12-29 15 01 20](https://cloud.githubusercontent.com/assets/447804/5574103/07974e2c-8f6c-11e4-93fd-af2006d3a44f.png)

**Comment by 130s** [comment]
Well turned out the clock of the VIRTUAL MACHINE I was using was 2 hours behind from the host machine, which seems very suspicious to me. Now I correct the clock and this issue doesn't happen. So I close this for now. Sorry for the noise (it still doesn't explain why there was 11 hours difference in my first post though)!
