### ISSUE TITLE
Google is doing away with OpenID 2.0

### ISSUE THREAD

**Issue by mikeferguson** [ros-infrastructure/answers.ros.org#109]
When logging into answers.ros.org -- I got a warning about this: https://support.google.com/accounts/answer/6135882

**Comment by wjwwood** [comment]
From the site:

> Starting April 20, 2015, OpenID 2.0 will no longer work for Google Accounts.

**Comment by evgenyfadeev** [comment]
todo: try to pull email from old google accounts then match with the email from the new account.
look how to make an announcement for users who might login via google.

**Comment by tfoote** [comment]
This migration has been completed. If anyone cannot get into their account please contact me and I can reset your email to get a password recovery.
