### ISSUE TITLE
(Enhancement) Mandatory "env" info upon asking a new question

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#110]
It will help expedite the answering process for some questions if the OP already posted `env` info.

In all forum posts of Baxter Research Robot, a footnote looks like the following. Even the [new question post window](https://groups.google.com/a/rethinkrobotics.com/forum/#!newtopic/brr-users) already suggests it:

```
___________________________________________
For issues, please run:
$ env | grep ROS
<...paste output here...>
```

So adding the similar message to http://answers.ros.org/questions/ask/ might help.

**Comment by gavanderhoorn** [comment]
I'd go a bit further, and make info on ROS version, how it was installed, OS and OS version, cpu architecture, etc also 'mandatory'.

Can't remember how many times I've asked this of posters.

**Comment by gavanderhoorn** [comment]
To get something in place quickly, without needing to change a lot of infrastructure: could we perhaps just update the bulleted list that is shown on the new question page (_Please ask your question here_)?

Right now it just says:

> - ask a question interesting to this community
> - provide enough details
> - be clear and concise
> - Guidelines for asking questions can be found at [wiki.ros.org/Support](http://wiki.ros.org/Support).

It would probably help already if the _provide enough details_ bullet would say things like: OS, ROS version, method of installation, etc.

**Comment by 130s** [comment]
@tfoote @evgenyfadeev Is there any reason that makes implementing this difficult, or undesirable? Together with #69?

If we just need a consensus of the information to be presented on the web page, I can draft and have it reviewed.

**Comment by gavanderhoorn** [comment]
@130s: shall we just go ahead with this? I find myself starting to skip questions when they don't have the above mentioned info-bits.

Having 'comment templates' (_please add .._) might also be an alternative ;).

**Comment by tfoote** [comment]
Thanks a more complete suggestion would be appreciated.

**Comment by tfoote** [comment]
We seem to have lost that minimal prompt. I've just made the question prompt much more full with a large excerpt from the support guidelines. I think requiring a specific data input with validation will likely be more work and effort than benefit. 

![image](https://user-images.githubusercontent.com/447804/35320108-8495218e-0097-11e8-81ea-49fb55c2cc0f.png)

Hopefully this will help improve the question quality.

**Comment by gavanderhoorn** [comment]
It's an improvement, but it might also be already too long and make people skip the whole thing.

Should this be condensed into just two bullet lists with `Do` and `Don't` above them?

We can link to the support guidelines of course if we feel that is necessary.
