### ISSUE TITLE
Page sorting is unavailable

### ISSUE THREAD

**Issue by l0g1x** [ros-infrastructure/answers.ros.org#112]
When I go to the answers.ros.org home page, it works fine. however, if i try to go to page 2,3,4, etc... I got a page saying service unavailable:

```
Service unavailable

This service is currently unavailable.

Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.
```

Tried multiple browsers (Chrome, Safari, Firefox) since yesterday afternoon-ish. 

For example: 

works 
- http://answers.ros.org/questions/scope:all/sort:activity-desc/page:1/

doesnt work 
- http://answers.ros.org/questions/scope:all/sort:activity-desc/page:2/
- http://answers.ros.org/questions/scope:all/sort:activity-desc/page:3/

May be some maintenance, but just wanted to report this incase it wasnt.

**Comment by tfoote** [comment]
Thanks I've confirmed that I can reproduce this. @evgenyfadeev FYI

**Comment by evgenyfadeev** [comment]
Fixed, sorry for the inconvenience.
