### ISSUE TITLE
User pages give server error

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#113]
When browsing any user's page besides my own such as [this one](http://answers.ros.org/users/122/dornhege/) I get 

```
Service unavailable
This service is currently unavailable.
```

**Comment by r1d1** [comment]
Same for me.

**Comment by gourneau** [comment]
Same here. Is there anyway we could see the server logs?

**Comment by MutantFreak** [comment]
As a logged out user, I get that error message on all user pages, even yours @tfoote.

**Comment by trainman419** [comment]
I've reported this upstream: https://github.com/ASKBOT/askbot-devel/issues/450

**Comment by evgenyfadeev** [comment]
Fixed, it was library version incompatibility, updated the library.
