### ISSUE TITLE
Comment isn't added

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#114]
I've posted more than a few comments on [this thread](http://answers.ros.org/question/207054/cant-start-turtlebot_worldlaunch-in-indigo-gazebo/) (in a trial to post a single comment) but none of them appears.

**Comment by 130s** [comment]
Looks like this issue is not limited to the thread I mentioned above. See http://answers.ros.org/question/207089/why-are-my-comments-on-ros-answers-disappearing/

**Comment by KyleKotowick** [comment]
I have been experiencing this issue as well, and can confirm that it exists.

**Comment by tfoote** [comment]
@evgenyfadeev FYI

**Comment by gavanderhoorn** [comment]
This is a bit of a _me too_, but this is rather an issue as it leads people to start abusing answers as comments. Seems it started after the recent upgrade?

**Comment by evgenyfadeev** [comment]
Hopefully it's fixed now, could you please try?

**Comment by KyleKotowick** [comment]
Seems to work for me now.

**Comment by gavanderhoorn** [comment]
Are comments posted before the fix lost, or can they be restored?

**Comment by evgenyfadeev** [comment]
They have not been recorded due to the bug, so they are lost.

On Wed, Apr 15, 2015 at 3:26 PM, G.A. vd. Hoorn notifications@github.com
wrote:

> Are comments posted before the fix lost, or can they be restored?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/114#issuecomment-93521257
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
Testing working
