### ISSUE TITLE
"Search" field returns error (but results are shown in a suggestion list)

### ISSUE THREAD

**Issue by r1d1** [ros-infrastructure/answers.ros.org#116]
When searching for keywords on the search field, existing topics are proposed, but when clicking on the search button (or hitting "enter"), I end up on the error page :

```
Service unavailable

This service is currently unavailable.

Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.
```

Reproducing : search some words in the search field, hit "enter".

**Comment by stwirth** [comment]
Same for me.

**Comment by tfoote** [comment]
@evgenyfadeev FYI

**Comment by evgenyfadeev** [comment]
Hopefully fixed now.

On Wed, Apr 15, 2015 at 3:59 PM, Tully Foote notifications@github.com
wrote:

> @evgenyfadeev https://github.com/evgenyfadeev FYI
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/116#issuecomment-93532463
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
tested working

**Comment by r1d1** [comment]
Perfect ! Thanks !
