### ISSUE TITLE
Authentification failure error messsage not working on answers.ros.org

### ISSUE THREAD

**Issue by ffurrer** [ros-infrastructure/answers.ros.org#117]
When going on http://answers.ros.org/account/signin/ and trying to log in via ROS Answers user name and password I end up on (occurred yesterday and today):

> **Service unavailable**
> 
> This service is currently unavailable.
> 
> Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

Cheers
Fadri

**Comment by gallagth** [comment]
Same here when login with user name and password

**Comment by jarvisschultz** [comment]
I'm having the same issue. I used to use Google OpenID to login, and now that option is no longer supported as reported in issue #109. It seems possible that the disappearance of OpenID the not being able to login with a password are related.

**Comment by tfoote** [comment]
Thanks for letting us know. So to confirm when the problem is, it is after you've entered a password when you would expect it to authenticate and then take you to the page you requested? 

I'll ping @evgenyfadeev

**Comment by ffurrer** [comment]
Yup, doesn't matter from where you go to the signin page and then entering any credentials, as demonstrated below with `a` as username (and `b` as password), when you then click the `sign in` button. (tested on chrome and safari)
![ros_signin_failure](https://cloud.githubusercontent.com/assets/917816/7352950/0b740a92-ed10-11e4-97bb-259565c50d01.png)

**Comment by jarvisschultz** [comment]
Note that I just used the `Recover account` link with the email address set in my profile, and it immediately sent me a recovery link. It then let me re-setup my Google login, and that is now working again.

**Comment by ffurrer** [comment]
yup, worked for me as well.

**Comment by tfoote** [comment]
Thanks I can reproduce. It's giving the error on the failed authentication screen.

**Comment by evgenyfadeev** [comment]
Fixed.
