### ISSUE TITLE
Can't revoke downvote on answer

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#119]
I downvoted http://answers.ros.org/question/208126/two-nodes-with-common-base-class-declaring-a-namespaced-service-path/?answer=208130#post-id-208130 because the original answer was not explained well. Now that the author has updated their answer, I would like to revoke my downvote, but I cannot.

Please fix.

**Comment by tfoote** [comment]
I changed the limit for revoking votes to unlimited. Can you do it now?

**Comment by trainman419** [comment]
Confirmed fixed. Thanks!
