### ISSUE TITLE
Can't recover account

### ISSUE THREAD

**Issue by paulbovbel** [ros-infrastructure/answers.ros.org#120]
I can't login through google or use the 'recover account' feature - reports that my email is not in the database. Is there anything I can do to recover?

http://answers.ros.org/users/3632/paulbovbel/

**Comment by paulbovbel** [comment]
Would an admin be able to manually trigger a recovery email? Alternatively, would appreciate a bump in karma on http://answers.ros.org/users/22411/pbovbel/ so that I can again edit, moderate, etc.

**Comment by paulbovbel** [comment]
@evgenyfadeev, thanks for merging the accounts. Whenever I try to login or recover, I end up with:

Service unavailable

This service is currently unavailable.

Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

**Comment by evgenyfadeev** [comment]
@paulbovbel I think your account is fixed. Please let me know if there are further issues, and reopen the issue in that case.
