### ISSUE TITLE
Service unavailable response when clicking on (docker?) tags

### ISSUE THREAD

**Issue by ruffsl** [ros-infrastructure/answers.ros.org#123]
Clicking on at least the `Docker` or `docker` tags from from anywhere on the site leads to an error in the form of a page displaying just:

![image](https://cloud.githubusercontent.com/assets/2293573/8759351/13ea33dc-2ca7-11e5-8f14-3b09d78c09a4.png)

> Service unavailable
> This service is currently unavailable.
> Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

Logged in, logged out, Firefox, Chrome; all exhibit the same behavior.
Did the database for the just this tag go bad?

pinging @dirk-thomas @tfoote

**Comment by evgenyfadeev** [comment]
Fixed the symptom, looking for what is causing this.

**Comment by tfoote** [comment]
Closing as this is working.
