### ISSUE TITLE
Closed Gazebo questions direct users to gazeboism.org instead of gazebosim.org

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#126]
Title says it all. After closing a question as off-topic because it's really just a Gazebo question, the text in the emblem (?) says:

> Closed for the following reason Gazebo Question: The Gazebo community prefers to answer questions at: http://answers.gazeboism.org by ..

Clicking the link tries to take users then to a non-existent domain.

**Comment by tfoote** [comment]
Fixed spelling
