### ISSUE TITLE
answers.ros.org has bad SPF record

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#128]
It looks like the SPF record for answers.ros.org is incorrect:

```
$ host -t TXT answers.ros.org
answers.ros.org descriptive text "v=spf1 ip4:140.211.15.247/32\004~all"
```

It looks like there's an odd `\004` character in there, where there should be a space.

This is causing all emails from answers.ros.org to fail the SPF/DMARC check and go into my spam box.

AOL already implements DMARC to cut down on spam; Gmail and Yahoo will be implementing DMARC in the near future, so this will start affecting other users as well: http://www.pcworld.com/article/2995524/security/google-yahoo-tighten-spam-filtering.html

**Comment by tfoote** [comment]
Yeah, that's odd. Gmail is checking the spf records and in my inbox it's passing even with the current entry. The `\004` is definitely out of spec.  I'll ping our hosting to fix the record though.

**Comment by tfoote** [comment]
Fixed. There was an escaping problem in the entry template.

**Comment by trainman419** [comment]
Fix confirmed! answers.ros.org emails are no longer ending up in my spam folder, and I can confirm from the message headers that they're passing the SPF and DMARC checks now.
