### ISSUE TITLE
Links with parentheses in URL not working correctly 

### ISSUE THREAD

**Issue by jarvisschultz** [ros-infrastructure/answers.ros.org#133]
I was just writing [this answer](http://answers.ros.org/question/232598/how-to-access-and-use-skeleton-joint-coordinates-using-openni-asus-xtion-and-ros/?answer=232618#post-id-232618) and links to sites that end in a ')' were not working correctly. They appear to work in the preview window, but they don't work when the answer is submitted. As a workaround I used [this answer](http://answers.ros.org/question/12729/how-to-link-urls-with-parentheses-correctly/?answer=18785#post-id-18785) to escape the '(' and ')' in the url.  It seems there was already a bug report about this back on trac, but I have no idea if it was ever fixed.

**Comment by tfoote** [comment]
This is an issue for upstream askbot. If it's still an issue please file it with the upstream project.
