### ISSUE TITLE
Opening 'karma' sub page of profile hangs browser

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#136]
Minor, but since beginning of this week (possibly end of last week?) I cannot open the _Profile - User's Karma_ page anymore. Well, I can open it, but after a nr of seconds at 100% CPU Firefox asks me whether I want to stop the Javascript that is running at that point. The karma page has never been the quickest for me, but Firefox has never complained about it like it does now.

Choosing to stop the script results in a semi-working page: the graph isn't shown, but the _change log_ is.

Was something updated/changed?

**Comment by tfoote** [comment]
@evgenyfadeev  I can confirm problems on chromium too. I didn't get a problem script but the page took 40 seconds to load and the graph never rendered. 

![image](https://cloud.githubusercontent.com/assets/447804/16313115/aa7cfea0-392c-11e6-91a3-381f922da1f2.png)

**Comment by evgenyfadeev** [comment]
@tfoote I'm working on the fix. The issue is that the karma history is too long and askbot is serving it whole.

**Comment by tfoote** [comment]
That makes sense, our history has been building up for a while. Thanks

**Comment by evgenyfadeev** [comment]
fixed, now taking a sampling of up to 150 points to display.

**Comment by tfoote** [comment]
Great, it's working for me now.
