### ISSUE TITLE
Reports that users can't edit their own question after it has been commented on or answered

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#137]
From [i can't edit my question](http://answers.ros.org/question/237993/i-cant-edit-my-question/) fi.

Not sure if it has anything to do with the fact that these are relatively new accounts (< 100 karma).

**Comment by gavanderhoorn** [comment]
Also reported on [How to install ROStful ?](http://answers.ros.org/question/237972/how-to-install-rostful/)

**Comment by evgenyfadeev** [comment]
Fixed, there was an error in determining which edit links to hide.

**Comment by rlefevre1** [comment]
Thanks, it works properly for me now

**Comment by bskyldz** [comment]
thank you, now editing works for me

**Comment by gavanderhoorn** [comment]
Seems this can be closed.

Thanks @evgenyfadeev for fixing it.
