### ISSUE TITLE
Clicking 'See more comments' makes all but a single comment disappear?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#138]
See [How to install ROStful ?](http://answers.ros.org/question/237972/how-to-install-rostful/) fi.

Clicking on _see more comments_ seems to hide all comments but the first. Clicking it again duplicates that comment.

Reloading the page restores the comment list.

Both Firefox (v47, logged in) and IE (11, not logged in) display this behaviour.

**Comment by evgenyfadeev** [comment]
fixed.

**Comment by gavanderhoorn** [comment]
Seems to work again. Was this a regression?

**Comment by evgenyfadeev** [comment]
yes, messed this when working on the missing "edit" links for some users.
