### ISSUE TITLE
No notifications for last few days

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#139]
I haven't received any notifications for the past few days.

I was browsing and noticed edits and comments on this post, which did not trigger a notification for me: http://answers.ros.org/question/241695/a-robot-should-stop-moving-if-cmd_vel-is-stopped-publishing-or-if-stop-command-send/

If this affects me, it probably affects other users too.

**Comment by tfoote** [comment]
Thanks for noticing. I too haven't received notifications since early August 12th.

**Comment by evgenyfadeev** [comment]
Working on this, should normalize by tomorrow, will keep an eye on this issue for some time.

**Comment by tfoote** [comment]
Thanks they're coming in and seem to be catching up.
