### ISSUE TITLE
"must be unicode, not str" error in the Interesting Tags textfield

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#140]
For instance, typing in `moveit`, then click `add` button yields the error in the title. Also tried `catkin` but the same result.

I tried on http://askbot.org/ (with `akismet` as a tag) and it seems to work there.

**Comment by tfoote** [comment]
I have the same problem @evgenyfadeev 

![image](https://cloud.githubusercontent.com/assets/447804/18927097/4495eacc-856f-11e6-980d-db2e5e307930.png)

**Comment by evgenyfadeev** [comment]
fixed
