### ISSUE TITLE
Remove MoveIt! from closure reason 

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#142]
MoveIt! maintainers decided to use answers.ros.org as its question forum (ref. https://github.com/ros-planning/moveit.ros.org/pull/78). We'll soon make an announce to its userbase.
Please remove the option for MoveIt! that was added in https://github.com/ros-infrastructure/answers.ros.org/issues/102 

cc @davetcoleman @IanTheEngineer @v4hn

**Comment by davetcoleman** [comment]
+1

**Comment by evgenyfadeev** [comment]
Done.
