### ISSUE TITLE
Allow linking to questions by ID

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#145]
(not sure if this is already possible or not, can't seem to find any docs on the markup Askbot supports)

It would be nice if we could link to other questions on `answers.ros.org` just by their numerical ID, similar to how this works on github for issues and PRs (`#id`) and Gitlab (`!id`, etc). Would save a lot of characters (especially in comments) and would make referring to duplicates and related questions easier.

It would be nice if the ID of questions would then also be easy to find (for copy/pasting).

On rendering the page, Askbot would expand the numerical reference with the title of the question.

**Comment by 130s** [comment]
This would be a great feature.

I think it's already implemented on [askubuntu.com](http://askubuntu.com) (so presumably on stackoverflow.com too).

**Comment by evgenyfadeev** [comment]
I've configured this so that `#q<question-id>` will be replaced with a corresponding link. It does not load the title though, just the plain link.

**Comment by gavanderhoorn** [comment]
Nice, awesome @evgenyfadeev ✨ 🎆 🍻 .

Could I be extra greedy and ask for an easy way to copy question IDs? Perhaps a button near the top of the page or something (similar to how github lets you copy commit hashes)?

**Comment by 130s** [comment]
Where on a page do we see the links?

For example, [page-1](http://answers.ros.org/question/219575/raspberry-pi2-roscpp-failed-during-indigo-installation/) is linked from [page-2](http://answers.ros.org/question/251140/compile-erros-installing-kinetic-on-pi-2-jessie/) but I might not be seeing each page is linked from the other.
