### ISSUE TITLE
"Service Unavailable" often happens

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#150]
While http://status.ros.org/ says answers has been up for 100%, I've seen the message a few times in the last 2 hours and http://www.downforeveryoneorjustme.com/answers.ros.org says it's not just me when I saw the message.

**Comment by evgenyfadeev** [comment]
@130s load average shows a number > than number of cpus (two at the moment). That would explain it. Looking into enabling caching of anonymous pageviews, that should help a bit, but would it be possible to give it more CPU cores?

**Comment by 130s** [comment]
I just noticed that you @evgenyfadeev edited your comment with more info, which no one notices unless opening this website. So just citing it below:

> load average shows a number > than number of cpus (two at the moment). That would explain it. Looking into enabling caching of anonymous pageviews, that should help a bit, but would it be possible to give it more CPU cores?

@tfoote?

Personally I haven't seen this issue since I opened this ticket BTW.

**Comment by evgenyfadeev** [comment]
@130s I've enabled the view caching for anon users and it might have taken down the cpu usage. We could  wait a bit and maybe revisit the scaling solution a bit later. It could be adding a cpu or moving the database on a separate host.
