### ISSUE TITLE
enhancement: add a "trivial change" checkbox for edits to posts (like we have for comments)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#151]
Subject says it all really: it would be nice if we could have some way to edit posts (fixing formatting fi, or minor typos) without notifying everyone who follows that post (either because they clicked *follow* or because they've posted a comment or an answer).

I typically edit questions because the formatting is not as it should be (especially when (first-time) posters include console copy-pastes) and that doesn't necessarily need to be broadcast around.

This would be similar to the "Trivial Change" checkbox we have on the ROS wiki.

**Comment by 130s** [comment]
+1 for this enhancement.

BTW other moderators' diligence like adding the most trivial changes like formatting could motivate others like me, so personally I don't mind particularly getting notified for the formatting :)

**Comment by gavanderhoorn** [comment]
Yes, well, I got some comments about the many email notifications I'm responsible for, so .. ;)

**Comment by gavanderhoorn** [comment]
Not seeing this happening.

So closing.
