### ISSUE TITLE
enhancement: allow 'splitting off' answers into new questions

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#152]
Would be nice if we could convert answers in hijacked Q&A's into questions directly, without having to tell the poster to "please don't post answers for follow-up questions" and then have them open a new question themselves.

Perhaps admins/moderators with sufficient karma could get an additional option under the *more* drop-down?

**Comment by 130s** [comment]
The feature that converts an answer into question-comment is so convenient (despite number of character limitation). So +1 for the feature suggested here too.

**Comment by gavanderhoorn** [comment]
Not seeing this happening, so closing.
