### ISSUE TITLE
Non existent URL: http://answers.ros.org/Support

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#153]
"Support" link leads to this:

![answers_support_notfound](https://cloud.githubusercontent.com/assets/1840401/24215513/414e88cc-0ef6-11e7-981f-8e10fb6fd3ae.png)

**Comment by 130s** [comment]
Likewise, https://discourse.ros.org/Support from discourse is not found either.

**Comment by tfoote** [comment]
Both links should be fixed now, with the full url not just a relative one.
