### ISSUE TITLE
"Forum" to point to discourse.ros.org in the menu banner?

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#154]
Before Discourse-era I've heard many people pointed to `answers` as a forum. answers.ros.org itself used to claim so; it remains so in Google's index as in the image below although the pare in the search result no longer states so.
![google_forum_ros org](https://cloud.githubusercontent.com/assets/1840401/24215695/c13a07c8-0ef6-11e7-8bc2-667b24b1786f.png)

IMO "Discussion", or simply `Discourse` makes sense and clarifies better?

**Comment by tfoote** [comment]
I've updated the header to be Discussion Forum
