### ISSUE TITLE
enhancement: improve search / separate from 'ask your question'

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#155]
This has always been a thing, but somehow seems to become more of an issue lately: the number of duplicate questions. Not the duplicate questions reported in #107, but questions from new users that either haven't searched, or haven't been able to find a relevant Q&A.

I'm wondering whether the combined "Search or ask your question" box at the top of the page isn't confusing newcomers: the links in the dropdown it shows are actually links to older questions, but I can imagine that they are seen as 'suggestions' - similar to how Google shows suggestions for instance.

Would it be an idea to more clearly (visually) separate "searching through older questions" and "posting a new question"? Perhaps ROS Answers should get a proper 'search result' page, with a clearly distinct 'enter your query' landing page or something similar.

**Comment by gavanderhoorn** [comment]
Personally I actually never use the search on the site itself, but always Google with `site:answers.ros.org ..`.

**Comment by ayrton04** [comment]
+1
