### ISSUE TITLE
[new user creation] Ambiguous "This field is required" error

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#156]
Reported at https://github.com/ros-drivers/openni_launch/issues/31#issuecomment-314610460 by @blueeaglex

**Comment by tfoote** [comment]
I can't reproduce that. @blueeaglex do you have plugins disabling webpage elements?

This is what I get. 

![image](https://user-images.githubusercontent.com/447804/28107577-32f948b2-669d-11e7-8b6c-0c95fc374aca.png)

**Comment by blueeaglex** [comment]
Thank you for commiting the issue. @130s

**Comment by blueeaglex** [comment]
@tfoote 
I tried different internet explorer from MS ie to Chrome,firefox. 
But I can not see the checkbox.

**Comment by blueeaglex** [comment]
@130s @tfoote  I see. I just need an internet proxy in US, then I would be able to get the checkbox.
It's OK now! Thanks

**Comment by tfoote** [comment]
@blueeaglex glad to hear you're working. In general you don't need a US proxy, only 25% of the traffic for the site is from US IPs. Since this is working for you I'm going to close.
