### ISSUE TITLE
Enable gif upload / attachments?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#157]
Currently only `jpg` (and probably `png`) is allowed.

Could `gif` be added?

That would make it possible to embed short animations that don't need entire videos directly in the answer.

**Comment by gavanderhoorn** [comment]
Example Q&A where this could be useful: [when i study the rviz:Markers: Sending Basic Shapes (C++), i come across some problem: when i run this order: rosrun using_markers basic_shapes, it told me that "Please create a subscriber to the marker",so how to solve this problem?](http://answers.ros.org/question/267860).

**Comment by evgenyfadeev** [comment]
gifs can be uploaded
