### ISSUE TITLE
update answers.ros.org FAQ to have the ROS specific info  (ros ticket #3859)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#16]
It was lost in the upgrade

trac data:
- Owner: **tfoote**
- Reporter: **tfoote**
- Reported at: **Mon Feb 20 15:17:01 2012**
- URL: https://code.ros.org/trac/ros/ticket/3859

**Comment by tfoote** [comment]
[tfoote] Something like: The ROS Support Policy is outlined at <a href="http://www.ros.org/wiki/Support">http://www.ros.org/wiki/Support</a>

**Comment by evgenyfadeev** [comment]
Do you want to replace the FAQ content with that?

**Comment by tfoote** [comment]
I think we mostly fixed this with the link in item 3 of the FAQ.  Maybe we could just add a line at the top. 

This is a part of the ROS ecosystem please see the [Support Guidelines on the ROS wiki for more information](http://wiki.ros.org/Support)

**Comment by tfoote** [comment]
I added a link to http://wiki.ros.org/Support at the top of the FAQ
