### ISSUE TITLE
answers outage 20171208

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#164]
![screenshot from 2017-12-08 10-47-48](https://user-images.githubusercontent.com/1840401/33780366-54b34dc6-dc05-11e7-9a0a-e1831f126d70.png)

Just wanted to make sure that it's a known issue as I haven't received an update I think I usually have received previously.

**Comment by tfoote** [comment]
We're aware of it and working on it. If the status page is showing it's down we're getting alerts. We're reaching hardware limits of the current host and are looking at solutions.

**Comment by tfoote** [comment]
OSUOSL was migrating some other services on our shared host and was bogging down the IO. That migration has been finished and our service should be restored.
