### ISSUE TITLE
Answers.ros.org has been down since last night 

### ISSUE THREAD

**Issue by mlautman** [ros-infrastructure/answers.ros.org#165]
I don't see anything in discourse about scheduled maintenance

**Comment by tfoote** [comment]
https://status.ros.org/incidents/jfql57hvr474

**Comment by mlautman** [comment]
Thanks! for now I've been using [https://web.archive.org/web/*/https://answers.ros.org/](https://web.archive.org/web/*/https://answers.ros.org/)
