### ISSUE TITLE
feature: show username of user that marked post as 'offensive'

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#167]
Just cleared the moderation queue, but it was essentially a large part of the posts of today.

Not sure what is going on.

**Comment by trainman419** [comment]
It might be nice to be able to see who has flagged a post as offensive

**Comment by gavanderhoorn** [comment]
Yes, that would be nice.

**Comment by gavanderhoorn** [comment]
As per the suggestion of @trainman419: it would be very nice if moderators / users with sufficient karma could see which user marked a post as offensive.

Right now only the fact that a post was marked as such is visible, and it shows up in the moderation queue, but that's it.

**Comment by gavanderhoorn** [comment]
@evgenyfadeev: is this something that would be possible?

Recently had to clean out the queue and (re)approve a bunch of Q&As that someone flagged for no apparent reason again.
