### ISSUE TITLE
Landing page shows extra answers

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#168]
The landing page on ROS answers is showing more answers than are actually present on the questions.

Attached a screenshot of the landing page as it appears now, and of the first two questions on the landing page. Note that  the first question shows 2 answers and the second question shows 1 answer, but when viewing the questions they have 1 and 0 answers respectively (although the first question says "2 answers" above the answer)

![answers_landing](https://user-images.githubusercontent.com/103991/35590227-1428f9ea-05fe-11e8-93d4-badfde019804.png)

![answer_1](https://user-images.githubusercontent.com/103991/35590230-17335950-05fe-11e8-842f-61ab7b6b47c6.png)
![answer_2](https://user-images.githubusercontent.com/103991/35590236-1934a380-05fe-11e8-965a-19c3566a1ff0.png)

**Comment by gavanderhoorn** [comment]
This is probably 'my fault'. I did a "block user and delete content" to get rid of the viagra spam posted by [user31187](http://answers.ros.org/users/10811/user31187/ ).

Not sure how that account came through the new user moderation.

**Comment by gavanderhoorn** [comment]
Could be that the account was actually compromised: two of the three questions posted by that account (so not the answers) seem like they may have been legitimate, but have been edited into oblivion.

If the account was then taken over, it would explain why an account from 2014 suddenly starts posting viagra spam.

**Comment by trainman419** [comment]
This seems to be limited to a small number of questions; a compromised account seems likely.

This still indicates a bug in the answers server since it's counting answers that no longer exist.

**Comment by gavanderhoorn** [comment]
I agree. I just wanted to provide some context.

**Comment by tfoote** [comment]
This is likely a bug in the upstream askbot but I don't think it worth it for us to track separately. There's more user moderation work ongoing, hopefully this bug will be picked up in that refactor.
