### ISSUE TITLE
How to add/edit tags?

### ISSUE THREAD

**Issue by mgruhler** [ros-infrastructure/answers.ros.org#171]
This is more of a question than a bug, but I'm not sure if this is just me being stupid or what...

When I try to tag (or retag) a question, I always stumble upon the problem of the tags not being applied. Adding the tags after klicking the retag button, e.g. works, I chose some from the dropdown (see following screenshot)
![grafik](https://user-images.githubusercontent.com/1374204/41767419-d71ecb66-7609-11e8-95ce-99efa9720a6a.png)

But how do I save them? Klicking anywhere else but the tag line closes it and they are gone. I don't see a save button or anything. What am I missing? When asking a question I always stumbled upon the same problem and then, at some point, it just worked. But no idea what I did.

**Comment by evgenyfadeev** [comment]
Hi, just hit "enter" when done editing the tags.
Cheers!

**Comment by mgruhler** [comment]
I tried this as well. But it still does not help...

Evgeny Fadeev <notifications@github.com> schrieb am Fr., 22. Juni 2018
16:46:

**Comment by mgruhler** [comment]
I was 100% sure I tried this multiple times. I probably got confused with the sometomes pretty slow autocomplete oft the tags... Closing
