### ISSUE TITLE
escape special characters in query  (ros ticket #3887)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#18]
http://answers.ros.org/question/29486/format-of-queryquestion-on-answersrosorg

trac data:
- Owner: **tfoote**
- Reporter: **tfoote**
- Reported at: **Sat Mar 10 22:26:28 2012**
- URL: https://code.ros.org/trac/ros/ticket/3887

**Comment by evgenyfadeev** [comment]
fixed
