### ISSUE TITLE
Disable/Reconfigure Feedback System

### ISSUE THREAD

**Issue by DLu** [ros-infrastructure/answers.ros.org#180]
The link at the bottom of every page (https://answers.ros.org/feedback/) sends emails to every moderator/admin (I believe) but I've almost never gotten anything useful from it, its mostly people complaining about some game (I'm guessing Rules Of Survival). 

Can we add some additional gatekeeping to this? [Logged in users only](https://askbot.org/en/question/8581/require-login-to-access-feedback-form/)? Captcha? Make them say what the R in ROS stands for? Or maybe just drop it all together, since there are other avenues (like this) to give feedback.

**Comment by tfoote** [comment]
I've setup a mailing list to archive the requests and we can decrease the subscriber list who recieves the notifications. 

@evgenyfadeev Do you know when we might be able to switch that over?

**Comment by gavanderhoorn** [comment]
Just received another "Rules of Survival" email asking where "the diamonds" are.

Any progress on this? @evgenyfadeev?

Should the devs behind Rules Of Survival be contacted so they can clarify what their support channels are to their customers and at the same time explain that `answers.ros.org` is not one of those?

**Comment by evgenyfadeev** [comment]
Sorry, yes it was settings -> feedback settings -> who receives feedback -> only authenticated users.
Now anon users can't fill out this form.

**Comment by gavanderhoorn** [comment]
@tfoote: is this something you need to change?

**Comment by tfoote** [comment]
It's already been changed. The feedback button is only available when you're logged in.

Logged out:
![image](https://user-images.githubusercontent.com/447804/51936332-cce69c80-23bc-11e9-9cff-f9a7c86183ae.png)

Logged in: 
![image](https://user-images.githubusercontent.com/447804/51936372-de2fa900-23bc-11e9-995a-468ae75aacae.png)
