### ISSUE TITLE
Consistent "internal server error" upon opening profile page

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#181]
Not much to add: I get repeatable "internal server error" pages when trying to open my profile page.

I wrote "intermittent" in the issue title as it doesn't always happen (as in: some days it's fine). But if it happens, it will always happen after that.

**Comment by gavanderhoorn** [comment]
Similar issue (from 2015): #113.

**Comment by gavanderhoorn** [comment]
Still getting this, but I noticed it only happens on the `overview` page for me.

Could this be something like #136?

**Comment by gavanderhoorn** [comment]
This is still an issue and makes referring back to older Q&As rather difficult: I have to use Google to find my own posts (so I can avoid duplicates).

**Comment by gavanderhoorn** [comment]
This is still an issue, @evgenyfadeev?

**Comment by gavanderhoorn** [comment]
Just noticed the error only occurs when I'm logged in.

**Comment by evgenyfadeev** [comment]
@gavanderhoorn that's on the overview of your user profile or someone else's? Could you give me a link please?

**Comment by gavanderhoorn** [comment]
My own profile: [link](https://answers.ros.org/users/5184/gvdhoorn).

---

Edit: oh, now it does load the page. Takes a while to load the page though.

@evgenyfadeev: has something been changed since 2 days ago?

**Comment by gavanderhoorn** [comment]
I'm closing this, as it doesn't appear to occur any more.

Loading my profile page does take upwards of 15 seconds sometimes, so there's probably something not entirely ok there @evgenyfadeev.

**Comment by evgenyfadeev** [comment]
@gavanderhoorn yes I did make certain data scan and identified three problematic questions. I'll have a look at the long loading time.
