### ISSUE TITLE
"export data" hangs forever

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#182]
Could be I'm just too impatient, but after waiting quite a while nothing seemed to happen.

Should this be reported upstream?

**Comment by evgenyfadeev** [comment]
looks like there needs to be an update to handle accounts with a lot of data, will fix it within 4 days.

**Comment by gavanderhoorn** [comment]
Friendly *ping*.

**Comment by gavanderhoorn** [comment]
@evgenyfadeev: any idea? Still can't export my data.
