### ISSUE TITLE
answers.ros.org appears to be down

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-infrastructure/answers.ros.org#183]
I'm getting this when going to it:

Service unavailable
This service is currently unavailable.

Please try back a little bit later. If there is a system outage you can see the status at https://status.ros.org/. If this is for a specific page or operation and is repeatable please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

**Comment by evgenyfadeev** [comment]
Probably a temporary network issue, as the app server is up and good shape.

**Comment by tfoote** [comment]
Looks like a temporary glitch, closing.
