### ISSUE TITLE
feature: support for 'details' section?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#186]
It might be nice if we could get support for the `<details></details>` tags such as is currently supported on Github in comments and issues & PRs.

Quite a few posts include verbatim copies of code and console text and that can get quite long, making posts harder to read.

If it were possible to include such large pieces of text, but collapse them somehow, that would improve readability of posts quite a bit.

**Comment by gavanderhoorn** [comment]
Good example of a question for which this would be perfect to have: [Unable to load ROS2 workspace into CLion](https://answers.ros.org/question/319753).

**Comment by tfoote** [comment]
Refiled upstream as this isn't specific to our instance of askbot

https://github.com/ASKBOT/askbot-devel/issues/842
