### ISSUE TITLE
New spam style

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#189]
Spotted a new style of spam today. This post was created about two months ago and looked like a genuine question, but was edited today to be some kind of advertisement: 313327

I don't think anything about our moderation style needs to change; just thought other moderators should know so that they can be on the lookout for this kind of thing.

**Comment by tfoote** [comment]
Thanks for flagging it @trainman419 that's definitely a new approach. I do hope that our notifications are enough to catch this sort of attack and that people flag them appropriately. I'll close this for now as there's no real follow up.
