### ISSUE TITLE
consistent "internal server" errors upon posting answers

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#191]
I'm getting consistent *Internal Server Error*s upon posting answers. This started today (ie: 2019-06-03, ~9am CEST).

The answers do appear to be actually posted.

Two questions this has happened on: `324516`, `324495`, `324533`, `324549` and `324574`.

**Comment by tfoote** [comment]
I think you hit just during the DNS switchover between the old and new host. If there's still an issue please comment back here.

**Comment by gavanderhoorn** [comment]
Just happened again with `324627`.

**Comment by gavanderhoorn** [comment]
As I'm a nobody I can't re-open this ;)

**Comment by evgenyfadeev** [comment]
Hi @gavanderhoorn is this still happening? I was unable to reproduce this on a replica site.

**Comment by gavanderhoorn** [comment]
I've not experienced this particular problem any more since the last time I reported it.
