### ISSUE TITLE
Image uploads appear to be failing (links result in 404s)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#192]
Not sure what is going on, but in two questions now the authors have been unable to attach images to their questions.

IDs of affected questions: [324648](https://answers.ros.org/question/324648) and [324623](https://answers.ros.org/question/324623).

Checking the links to the images manually results in `404`s:

 - https://answers.ros.org/upfiles/15596569309450913.png
 - https://answers.ros.org/upfiles/1559644022253663.gif

has something changed?

**Comment by tfoote** [comment]
I see the images embedded now and the urls show the images now too. We just upgraded the server. There may have been some hiccups associated with that. If there's still an issue, maybe with new images uploading and then becoming visible later please comment back here.
