### ISSUE TITLE
"403 Forbidden: CSRF verification failed" upon login

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#197]
Not sure this is actionable (as all I have is a screenshot), but I just (approx 9:05am CEST) encountered a `403: Forbidden` error when trying to log in:

![Screenshot_2019-07-08 403 Forbidden](https://user-images.githubusercontent.com/4550046/60789453-7184bb80-a15f-11e9-8bc6-7c98819e0db8.png)

I had to completely close my browser and reload the site before I could login again.

May have been something local, but I can't remember ever having ran into this before, so I wanted to report this here.

**Comment by tfoote** [comment]
Thanks I suspect this was an issue with our migration or site update that caught you. I'm going to close this and if anyone sees it again please comment back and we can reopen.
