### ISSUE TITLE
Sorry, this account recovery key has expired or is invalid

### ISSUE THREAD

**Issue by liborw** [ros-infrastructure/answers.ros.org#198]
When trying to recovery password,I have entered my email address in the password recovery form, I got email (title: Validate your ROS Answers email), clicked the link the minute I got the email and got "Sorry, this account recovery key has expired or is invalid", repeated twice with the same result.

**Comment by tfoote** [comment]
FYI @evgenyfadeev This looks similar to the registration issue.

**Comment by evgenyfadeev** [comment]
This has been resolved.
