### ISSUE TITLE
New spam campaign: duplicates of actual posts by new accounts

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#199]
Seen this with two posts now: [331541](https://answers.ros.org/question/331541) and [331327](https://answers.ros.org/question/331327).

A new account posts an -- on first glance -- legitimate question. Email address doesn't look like a spam account immediately, and post is a "normal" one.

No immediate activity after approval of the user account.

However, the content of the post is always an (almost) 100% copy of an older post, and there is no interaction with the poster after the first post.

This made me suspicious so I googled the registered email address of the OP of [331327](https://answers.ros.org/question/331327). It turns up results from multiple "stop spam" web sites.

For now I've not removed the content, but only reverted the account status to "new user", so further contributions have to go through the moderation queue again.

**Comment by gavanderhoorn** [comment]
Third one: [amasbrown](https://answers.ros.org/users/45167/amasbrown/).

**Comment by gavanderhoorn** [comment]
Potentially another one: [331788](https://answers.ros.org/question/331788).

**Comment by tfoote** [comment]
Crap, that's going to be a problem. This is going to get around our moderation approach. Thanks for catching this @gavanderhoorn

**Comment by gavanderhoorn** [comment]
And a nice new one: account that posted a regular question (cannot find a package), then returns about 2 months later and posts spam.

Post: [331191](https://answers.ros.org/question/331191) (appears to be a copy-paste of [331079](https://answers.ros.org/question/331079)).
Account: [hungns35](https://answers.ros.org/users/45007/hungns35).

I've *blocked and deleted all contents*.

![ros_answers_sshot](https://user-images.githubusercontent.com/4550046/66465270-d4e4f900-ea80-11e9-893c-3021b775e480.jpg)

---

Edit: apparently the user registered with an email address that occurs in the "stop forum spam" database for Vietnam.

**Comment by gavanderhoorn** [comment]
This is some pretty labour-intensive way of spamming fora (it wasn't even a complete duplicate, some of the content was changed, but still made sense as a question). Apparently still pays off.

**Comment by tfoote** [comment]
Wow that is a lot of effort. The edit changes are very hard for us to catch in moderation. We definitely need to resolve the registration validation issue. 

That's not a user that raised of the usual spammy flags. It could also have been a compromised account. But that seems unlikely with the duplicated initial content. It sounds like someone actually just using that account and manually creating the spam. I looked and in additon to being in the forum spam database that email is also listed as a contact point for a restaurant on a Vietnamese facebook page too. Hopefully Evgeny will have some upgrades for us soon.

**Comment by gavanderhoorn** [comment]
> Hopefully Evgeny will have some upgrades for us soon.

yes, that would be nice.

Are there any specific upgrades planned already?

**Comment by 130s** [comment]
I noticed recently GMail has started moving some notification emails from answers.ros.org into spam. I see almost multiple of those emails in spam folder every day. Not yet sure why it has happened but this elaborated spam may be related.

**Comment by tfoote** [comment]
@130s that's a completey different type of spam. 

Can you open a new ticket and show the headers from the emails that labelled as spam? They should tell you why it's being classified. Otherwise your local gmail client just may be noticing that you don't interact with them even if they're delivered appropriately which you can retrain by telling it tat they're not spam.

**Comment by gavanderhoorn** [comment]
It's been while, but [here](https://answers.ros.org/users/49982/alexdeborg/) is another account. They didn't waste any time: copied a post that was posted this morning and then added a spam link to it.

**Comment by gavanderhoorn** [comment]
And a new one: [awdnoi2](https://answers.ros.org/users/50948/awdnoi2/). This one copied posts from Reddit to ROS Answers.

**Comment by gavanderhoorn** [comment]
Looks like a new one: [buidiena3](https://answers.ros.org/users/52471/buidiena3/).

**Comment by gavanderhoorn** [comment]
New one: [minousoso](https://answers.ros.org/users/53409/minousoso/).

**Comment by tfoote** [comment]
And a new one [here](https://answers.ros.org/users/53618/sekodilemo/)

[Comment by EF: this one logged in with Google]

**Comment by gavanderhoorn** [comment]
And a new nice one: [lacazet2k](https://answers.ros.org/users/52524/lacazet2k).

[Comment by EF: this one posted a question copied from elsewhere, then edited with non-English text containing spam, long text, images, external links]

**Comment by evgenyfadeev** [comment]
1) Akismet antispam is disabled on the site. Perhaps enabling it will help, it is checking email address, ip andcontent.

It's in "settings" -> akismet spam protection. There is a key entered, but the feature is disabled.
Could someone please verify that they have an active akismet account, enable it and test how it works for you?

2) Will attempt to enable stopforumspam within a week - this solution is orthogonal to Akismet.

**Comment by gavanderhoorn** [comment]
@evgenyfadeev wrote:
> Comment by EF: this one posted a question copied from elsewhere, then edited with non-English text containing spam, long text, images, external links

yes, that is the case with *all* accounts and posts listed in this thread.

Is akismet going to help with this type of spam? All these accounts start as normal accounts, with normal questions and answers.

After they get through the moderation queue, they come back in a few hours/days and edit their previous posts to contain spam messages.
