### ISSUE TITLE
daily subscription system isn't working for me  (ros ticket #3347)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#2]
When I set the entire forum subscription rate to 'Instantly', I get messages as they appear, but when I set it to daily, say, I don't get any messages (have tried this for a few days).

trac data:
- Owner: **tfoote**
- Reporter: **bhaskara**
- Reported at: **Mon Feb 21 09:18:33 2011**
- URL: https://code.ros.org/trac/ros/ticket/3347

**Comment by tfoote** [comment]
[tfoote] I've updated my profile to daily for the entire forum. I'll see if I can reproduce and then report upstream.

**Comment by tfoote** [comment]
[tfoote] We need to call send_email_alerts from a cron job.  See http://askbot.org/doc/management-commands.html

Nathan, can you get this to happen?

**Comment by tfoote** [comment]
[tfoote] I've gotten the job working and added it to cron.  Please reopen if you see the same problem.

**Comment by tfoote** [comment]
[tfoote] I needed these details: http://askbot.org/en/question/316/what-permissionsenvironment-setting-are-needed-to

**Comment by tfoote** [comment]
[bhaskara] After receiving a digest message on Feb 24, I have received no further messages.  My settings are to get daily updates.

**Comment by tfoote** [comment]
[tfoote] Thanks, cron is a pain.  Hopefully i've debugged it now.

**Comment by tfoote** [comment]
[tfoote] ok, i just got an email that I didn't trigger by hand so i think it's working

**Comment by tfoote** [comment]
[bhaskara] I think this might have recurred.  My settings are to get updates daily, but the last one I got was March 16th.

**Comment by tfoote** [comment]
[mwise] what are your subscription settings?

**Comment by tfoote** [comment]
[bhaskara] attached.

**Comment by tfoote** [comment]
[bhaskara] Any update on this?  Or can you suggest a workaround?

**Comment by tfoote** [comment]
[ahornung] Notification still seem to be broken with the updated site. Didn't get any notification on a new question with my tags, ever. I have everything set to "Instantly" and checked "allow only selected tags". I only get notifications on my tags when someone else comments or answers the question, or it is edited.

**Comment by tfoote** [comment]
[tfoote] Adding Evgeny

**Comment by ahornung** [comment]
I can confirm that it's still not working properly (subscriptions are all set to "immediate"). I sometimes get notifications on my watched tags, but did not for this specific question: http://answers.ros.org/question/59028/octomapbinaryh-no-such-file-or-directory/

Only after someone else commented or posted an answer I got a notification.

**Comment by evgenyfadeev** [comment]
This issue is due to 15 points karma limit on triggering email alerts. I've lowered it now to 1, please let me know if you have a lot of spam messages fro the new users.

**Comment by dirk-thomas** [comment]
This has been resolved some time ago: http://code.ros.org/lurker/message/20130613.175850.542fd855.en.html
