### ISSUE TITLE
Required tags missing dashing, eloquent

### ISSUE THREAD

**Issue by rotu** [ros-infrastructure/answers.ros.org#200]
The required tags are missing dashing and eloquent:

> At least one of the following tags is required : boxturtle, cturtle, diamondback, electric, fuerte, groovy, hydro, indigo, jade, kinetic, lunar, melodic, r2b3, ardent, bouncy, crystal, ros1 or ros2

![image](https://user-images.githubusercontent.com/119948/64812596-2d4dd700-d565-11e9-938d-850834488b3b.png)

**Comment by tfoote** [comment]
Thanks. I added them and noetic
