### ISSUE TITLE
Add index.ros.org and robots.ros.org to allowed origins for CORS headers for the RSS

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#201]
I think that we used to have open access for the RSS feeds, but now they are getting blocked by CORS policy. https://github.com/ros-infrastructure/rosindex/issues/188

This has disabled access to the embedded lists on both index.ros.org and robots.ros.org where we've been listing relevant tag filtered questions to provide more visibility.

I'm also seeing this on robots.ros.org too. Random example: https://robots.ros.org/caster/
`(index):1 Access to XMLHttpRequest at 'https://answers.ros.org/feeds/rss/?tags=caster' from origin 'https://robots.ros.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by evgenyfadeev** [comment]
Added the header for any subdomain of ros.org

**Comment by tfoote** [comment]
Thanks, looks good to me.
