### ISSUE TITLE
After clicking on "more" to see a long question or answers, syntax highlighting of code blocks becomes disabled

### ISSUE THREAD

**Issue by cosmicog** [ros-infrastructure/answers.ros.org#203]
This is an issue that I see for a long time. I'm surprised that I couldn't find any related issues. Basically, after clicking **more** to see the whole long question, syntax highlighting is being disabled like this:
```cpp
try 
{
    std::vector<int> vec{3, 4, 3, 1};
    int i{vec.at(4)};
}
catch (std::out_of_range &e) 
{
    std::cerr << "Accessing a non-existent element: " << e.what() << '\n';
}
```
becomes this:
```
try 
{
    std::vector<int> vec{3, 4, 3, 1};
    int i{vec.at(4)};
}
catch (std::out_of_range &e) 
{
    std::cerr << "Accessing a non-existent element: " << e.what() << '\n';
}
```
For example: [Gazebo controller spawner warning - ROS Answers](https://answers.ros.org/question/214712/gazebo-controller-spawner-warning/
)

**Comment by tfoote** [comment]
Thanks for filing it and providing an example. This definitely looks like a bug. But I believe it's upstream and not an issue with the ROS deployment. To that end please refile it upstream at: https://github.com/ASKBOT/askbot-devel/issues
