### ISSUE TITLE
Add Foxy to 'Version Tags"

### ISSUE THREAD

**Issue by dawonn-haval** [ros-infrastructure/answers.ros.org#208]
Minor issue, described here: https://answers.ros.org/question/358952

The Instruction for tags is:
> "You must at least tag the rosdistro you are using, such as indigo, kinetic, lunar, melodic, or ardent."

The error text if you fail to comply is: 
> "At least one of the following tags is required : boxturtle, cturtle, diamondback, electric, fuerte, groovy, hydro, indigo, jade, kinetic, lunar, melodic, noetic, r2b3, ardent, bouncy, crystal, dashing, eloquent, ros1 or ros2"

shouldn't theses match? and why no love for Foxy? :)

**Comment by tfoote** [comment]
I added foxy galactic and rolling
