### ISSUE TITLE
ros.org domain name has expired

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/answers.ros.org#209]
All ros.org websites including answers.ros.org are unreachable with the following message on the page:
This Domain Name Has Expired - Renewal Instructions.

This also applies to packages.ros.org preventing people from using "apt update" if the ros repos are in their sources

@tfoote @nuclearsandwich FYI

**Comment by gavanderhoorn** [comment]
Everything is down basically.

Not seeing anything on Twitter either didn't help.

**Comment by mathias-luedtke** [comment]
Same as https://github.com/osrf/www.ros.org/issues/92

**Comment by gerkey** [comment]
Fixed now, apologies for the service interruption.
