### ISSUE TITLE
Items waiting in the moderation queue for 5+ days found frequently

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#210]
I think this is an extension of [ROS Answers needs your help (discourse.ros.org#5147) ](https://discourse.ros.org/t/ros-answers-needs-your-help/5147).

# Problem
I tend to access answers.ros.org every other day or so then almost always notice a good amount of items in the moderation queue. Sometimes I'd say many, as in 30+ items. Almost always, the time that some/many of those posts were posted is 10+ hours ago. 
This results in posts from new users not seen for that amount of time.

I'm afraid that could affect the new users to disappointment (they could feel frustrated, isolated etc.)

## Possible underlining problems
- Moderators don't know until they access the website that there's (a long) list of items. I remember there was at least one user who even sent "Site feedback" email and wondering why her/his/their post didn't show up on the website.
- Not sure if there are enough number of moderators who are willing to help regularly.
- Else?

**Comment by 130s** [comment]
I just cleaned up many items in moderator queue, some of which were posted 50+ hours ago.

**Comment by gavanderhoorn** [comment]
Since a few months now I've stopped moderating.

I'm not the only moderator of course, but I've noticed what you describe since I've stopped.

We may need to recruit more moderators.

**Comment by 130s** [comment]
In the past few of my moderation chores, I've always found 30+ hours posts.

Either we recruit more moderators as Gijs said, or is there better solution?

**Comment by evgenyfadeev** [comment]
If you have a lot of spam posts, an upgrade could help b/c there is a feature allowing do dismiss a screenful of posts by one click.

**Comment by gavanderhoorn** [comment]
Spam isn't really a problem (any more).

We just have too few moderators frequenting ROS Answers these days.

**Comment by 130s** [comment]
Update; I found queued questions for 5+ days today. Title updated.

I don't have time to check answers.ros.org regularly these days. I just feel sorry that this is happening.

@tfoote Do you have an update on this?

**Comment by 130s** [comment]
Just unblocked 10+ posts. Some were 30+ hours old, in the middle of a normal week.

**Comment by 130s** [comment]
Just unblocked about 10 posts, oldest of which was posted just 4 hours ago.

Because of planned migration [discourse.ros.org#28068](https://discourse.ros.org/t/planned-migration-of-ros-answers-and-gazebo-answers-to-robotics-stack-exchange/28068), however, I guess this won't be an issue soon.

Closing.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/would-it-make-sense-to-migrate-ros-answers-to-stack-exchange/17123/11
