### ISSUE TITLE
Gaining Karma by deleting a question?

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#211]
Not sure if this happened by design of the website.

<img width="815" alt="Screen Shot 2021-04-26 at 3 41 39" src="https://user-images.githubusercontent.com/1840401/116047337-d3f6c680-a628-11eb-8e4a-3910ad77b9e8.png">

**Comment by tfoote** [comment]
he didn't get karma by deleting the post. The post on which karma was earned has been deleted.
