### ISSUE TITLE
Site very unresponsive at times

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#212]
Similar to what we had in #196.

ROS Answers is -- at times, but often -- *very* slow to load.

For regular pages that's not too much of a problem, more an annoyance.

For anything which relies on ajax/the API, it leads to unclear UI interactions. I've noticed users posting questions and answers multiple times, duplicated comments and accepting/unaccepting/accepting/unaccepting/etc answers.

**Comment by tfoote** [comment]
Our growth curve continues, we're likely hitting hardware limits again at peak traffic times. I'll look into resource availabilty.

**Comment by evgenyfadeev** [comment]
it might be the database,  I will time some queries. The cpu load is  ~10%, ram usage < 50%. There was some swapping which I've disabled. It did help somewhat, especially in the worst cases, still 3s for the main page render is a lot.

**Comment by evgenyfadeev** [comment]
I've timed some queries from the main page, indeed they are slow, some take ~1s some > 1s.

I don't have access to the db server and cannot answer these questions - does it have enough RAM, CPU? Is the storage SSD, is there any IO latency?

**Comment by gavanderhoorn** [comment]
Seems to have improved.

It still fluctuates, but much better than approx 1 / 2 months ago.
