### ISSUE TITLE
(very) large nr of spam accounts created

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#213]
Just happened to take a look at [answers.ros.org/users/?sort=newest](https://answers.ros.org/users/?sort=newest). At least ~~two~~ ~~ten~~ thirty pages (~= 900 accounts) full of accounts registered in the past few days (I've seen accounts old as 2021-07-25) with nonsense bios full of links to external spam/advertising/phishing sites.

I saw some new accounts claiming to be from "the Netherlands", so I took a look. Nothing in those bios makes sense.

I've blocked & deleted a few, but there's too many.

Perhaps the admin can do this faster / easier.

**Comment by gavanderhoorn** [comment]
Example: [kiaraather](https://answers.ros.org/users/79205/kiaraather/).

**Comment by evgenyfadeev** [comment]
@gavanderhoorn I will try to resolve this within a week.

**Comment by gavanderhoorn** [comment]
And they've started posting spam:

![image](https://user-images.githubusercontent.com/4550046/128231658-b97dc86b-ecb6-4f67-85c0-7b7cde3bfdc2.png)

Account: [florenestr](https://answers.ros.org/users/79632/florenestr).

---

Edit: I've blocked the account and deleted the spam.

**Comment by evgenyfadeev** [comment]
I've found that Akismet was disabled, enabled it. Also I think I found a source of account spam (akismet not run on the user "about" section in one of the endpoints), will deliver this in ~3 days.

This will not reduce the number of the accounts created but should limit the spam posts.

I will research more on how to detect the spammers before they post anything using known spam databases etc.

**Comment by gavanderhoorn** [comment]
> I've found that Akismet was disabled, enabled it.

I'm not sure what's going on, but I've received at least one feedback message from a user which can't post anything at all, even though he's been through the moderation queue already, and I'm personally unable to post any comments:

![Screenshot from 2021-08-07 14-14-54](https://user-images.githubusercontent.com/4550046/128599799-8f0a3312-f8be-4d08-97fa-22373a2910fa.png)

Maybe Akismet is a little too "triggerhappy".

**Comment by gavanderhoorn** [comment]
I'd probably suggest disabling Akismet for now.

**Comment by tfoote** [comment]
For the longer story about account profile spam see #141 We need a better automated solution, this is just accelerating. 

I'm going to close this in favor of #141 with more information.
