### ISSUE TITLE
Internal server error from https://answers.ros.org/questions/tags:ROS1/

### ISSUE THREAD

**Issue by lucasw** [ros-infrastructure/answers.ros.org#217]
I spot checked a few other tags but couldn't find any with the same issue as https://answers.ros.org/questions/tags:ROS1/ , for example https://answers.ros.org/questions/tags:kinetic/ works fine and has many more results according to https://answers.ros.org/tags/ .

**Comment by mjs973** [comment]
There's something weird with the way this tag is handled. The backend remaps the string "ros1" to "ROS1", yet the tag system rejects it if a user types in "ROS1".

**Comment by lucasw** [comment]
Was the https://answers.ros.org/questions/scope:all/sort:activity-desc/tags:ROS1/page:1/ link working for you yesterday?  It *is* working for me now, no more `internal server error` (but not maybe a week ago last time I tried) - did something change?

**Comment by tfoote** [comment]
They all seem to be working now. Closing as something that was hopefully a regression and fixed in the next release.
