### ISSUE TITLE
Bait questions

### ISSUE THREAD

**Issue by robogeekcanada** [ros-infrastructure/answers.ros.org#218]
I noticed some questions are vague but have catchy titles, I closed one recently: `Can't open RViz Ubuntu 18.04`, the user is a new account and doesn't respond to comments but the views keep increasing. So I suspect they are trying to do is create traffic to their question as it will be ranked high in the google searches. 

Also I noticed and perhaps not new to anyone in the group that other sites are catching ROS answers making minor changes and directing to other sites in other languages.

**Comment by tfoote** [comment]
Thanks for cleaning up those questions. We've seen spammers who will repost old content to try to get through moderation too to gain trust too. 

And if you see sites ripping off answers.ros.org without giving credit please reach out to info@openrobotics.org  (Note that the content is CC BY SA so it is valid to repost if credited and still under CC BY SA)
