### ISSUE TITLE
Question vanished?

### ISSUE THREAD

**Issue by johnwason** [ros-infrastructure/answers.ros.org#219]
I asked a question about colcon earlier today and it doesn't appear in my account or the main list of questions. It said the question was submitted. I don't know if this is a bug or my question got caught in a spam filter?

**Comment by robogeekcanada** [comment]
Hi @johnwason I checked and your question is showing:

https://answers.ros.org/question/394564/rviz-moveit-plugins-not-loading-on-windows-10/

![image](https://user-images.githubusercontent.com/32141561/150347453-94e8e17e-baf5-4b07-97ff-f63bc0129a6e.png)

**Comment by johnwason** [comment]
That is not the title I gave for the question, which is why I am confused. Can I delete and try again?

**Comment by lucasw** [comment]
You can edit the title yourself to improve it (and moderators can change it also), that's better than deleting- or maybe you don't have enough karma?

I edited the title to this [question](https://answers.ros.org/question/219053) recently and it doesn't clearly show that in the revision history (and possibly no notifications) but at the same time the revision history shows the original title https://answers.ros.org/questions/219053/revisions/

**Comment by johnwason** [comment]
@lucasw ok I edited the title. It must have autofilled to an old question and I didn't notice.
