### ISSUE TITLE
Allow admins to accept answers without a time delay  (ros ticket #3935)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#22]
Currently admins have to wait n days to mark an answer as accepted. Instead, they should be able to do it immediately.

trac data:
- Owner: **mwise**
- Reporter: **damonkohler**
- Reported at: **Wed Apr 25 11:11:16 2012**
- URL: https://code.ros.org/trac/ros/ticket/3935

**Comment by dirk-thomas** [comment]
The time out has been shortened to 36 hours. This is intentional to not allow marking a question as answered "immediately" but others. The person filling the question can mark it answered any time.
