### ISSUE TITLE
enable search for 3 letters  (ros ticket #3977)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#26]
We have many 3 letter acronyms which would be great to be able to search over.

trac data:
- Owner: **mwise**
- Reporter: **tfoote**
- Reported at: **Sun Jun  3 13:51:48 2012**
- URL: https://code.ros.org/trac/ros/ticket/3977

**Comment by evgenyfadeev** [comment]
need to migrate to postgres (made a support request for this - to create a postgres database).

**Comment by trainman419** [comment]
+1

**Comment by tfoote** [comment]
We've switched over to postgres and shorter queries work now.
