### ISSUE TITLE
Karma growing when answers are accepted/not accepted/accepted...  (ros ticket #4046)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#30]
By repeatedly accepting, removing the accept flag, accepting again, etc, the karma of the user whose answer is accepted grows. Removing the accept reduces the karma by 5 while accepting adds 15. That means for each cycle the user gets 10 karma without actually being upvoted.

While this helps to increase my karma, I think it is definitely not intended behavior :)

trac data:
- Owner: **mwise**
- Reporter: **lorenz**
- Reported at: **Wed Sep  5 04:41:00 2012**
- URL: https://code.ros.org/trac/ros/ticket/4046

**Comment by bit-pirate** [comment]
The inverse behaviour emerges, when downvoting answers: downvote -2, remove downvote +1, ...

Has this been ticketed/asked on AskBot?

**Comment by felix-kolbe** [comment]
At least the downvote thing has been asked on askbot: http://askbot.org/en/question/10008/karmareputation-calculation-error-on-question-downvotes/

**Comment by tfoote** [comment]
I just tried this on a question and it rolled back correctly.
