### ISSUE TITLE
rss feed insufficient escaping produces invalid xml

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#32]
Happens every now and then, attaching todays result from  http://feedvalidator.org/check.cgi?url=http://answers.ros.org/feeds/rss/

From: https://code.ros.org/trac/ros/ticket/4017

https://code.ros.org/trac/ros/attachment/ticket/4017/check.cgi.html

**Comment by evgenyfadeev** [comment]
Tully - I have a question: is the issue warnings in the feed validator or
actually unusable feeds?

It seems to me we actually have valid feeds, but just have warnings in the validator,
which would be fine by me as long as users do not suffer from these warnings.

RSS format has limitations and we have complex content... so if needed we could
use alternative feed formats - if indeed it is important to support quality syndication.

**Comment by tfoote** [comment]
I think the invalid xml has been resolved.  I have a macro for embedding RSS feeds into the wiki, it works fine for planet.ros.org's feed http://wiki.ros.org/TullyFoote/TestPlanetRSS  but answers.ros.org's feed loses all it's layout http://wiki.ros.org/TullyFoote/TestAnswersRSS

**Comment by tfoote** [comment]
Now the feed is valid and not causing any problems, just warnings in the validator. It looks like code that is quoted with bracketed includes can be considered a xml tag sometimes, but that's generally not a problem for most readers. So I'm going to close this as works for me.
