### ISSUE TITLE
Navigate questions related to gazebo to gazebosim.org, not on answers.ros.org

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#33]
http://goo.gl/h57xe
Nate says regardless `ROS` related or not, all questions should be asked on `gazebosim`.

**Comment by 130s** [comment]
- [ ] Close unanswered questions that are `Gazebo`-centric. 
  - 10+ done but still way to go.
- [ ] Add banner or anything that stands out on answers.ros.org
- [x] Add banner or anything that stands out on tutorials
  - Delegated to https://github.com/ros-infrastructure/roswiki/issues/20

**Comment by evgenyfadeev** [comment]
Would you like to implement a two-portal setup off the same database?

**Comment by tfoote** [comment]
At this point I don't know if it's worth doing that.  The OpenID support makes it relatively low overhead to have the multiple instances.  It seems that this is generally sorting itself out.
