### ISSUE TITLE
Provide a READM.rst file in this git project

### ISSUE THREAD

**Issue by tkruse** [ros-infrastructure/answers.ros.org#35]
Going to this page does not tell users a lot of useful things. Esepcially new users who do not know github will miss that there is an issues tag:
https://github.com/ros-infrastructure/answers.ros.org

i suggest adding as source just a README.rst file that explains the purpose of this github project, and explains when bugs should be reported here as opposed to be reported in the askbot feedback.

**Comment by tfoote** [comment]
03e4ba2756148bce7b9d876167f1c99e782690bd done
