### ISSUE TITLE
Emailing Interesting Tags

### ISSUE THREAD

**Issue by davetcoleman** [ros-infrastructure/answers.ros.org#38]
From everyone I've talked to except @wjwwood, answers.ros.org does not send email notifications out when questions are asked with certain keyword tags of interest. This is hurting the ROS community because the best ppl to answer a question are not being notified their help is needed. What steps need to be taken to fix this emailing functionality issue?

Thanks!

**Comment by 130s** [comment]
+1

**Comment by tfoote** [comment]
Looking at the logs they appear to be going out correctly I suggest you check your spam filter.

**Comment by davetcoleman** [comment]
So it is!
