### ISSUE TITLE
notification emails lack subject prefix

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/answers.ros.org#39]
Since the relocation notification do not have the subject prefix `[answers.ros.org]` anymore.

**Comment by tfoote** [comment]
this is fixed. my emails now have this

**Comment by tfoote** [comment]
Sorry the new emails in my inbox were from pre-migration. This is still an issue.

**Comment by evgenyfadeev** [comment]
added setting, the prefix should come back

**Comment by dirk-thomas** [comment]
I guess this ticket can then be closed?

**Comment by tfoote** [comment]
I just got an email this evening with the prefix.
