### ISSUE TITLE
Code formatting broken

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/answers.ros.org#40]
See:

http://answers.ros.org/question/68278/jenkins-build-issues-file-install-cannot-find-obj-x86_64-linux-gnu/?answer=68431#post-id-68431

The `#` signs in the code snippet which should be comments in CMake, are rendered as headings in the output on the website. This was not the case before the move.

**Comment by evgenyfadeev** [comment]
This is invalid I think. The issue is that indented blocks just after the bulleted lists are interpreted as continuation of the list item.

**Comment by tfoote** [comment]
It looks ok now.
