### ISSUE TITLE
Link and stress not working in comment

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#42]
![answers ros org_comment_linknotworking](https://f.cloud.github.com/assets/1840401/846548/12e063d4-f415-11e2-98b1-da8ae777dbf6.png) (from [here](http://answers.ros.org/question/67345/build-debian-package-locally/)) after upgrade to `askbot` 0.7.48.

**Comment by tfoote** [comment]
comments aren't expected to have formatting to avoid significant content in the comments.  http://askbot.org/en/question/10091/why-do-comments-have-a-different-syntax-than-answers/

**Comment by bit-pirate** [comment]
According to the comments in the linked Q&A basic formatting functionality is now available for comments, but needs to be enabled. Could this be enabled on ROS Answers as well. 

IMO basic formatting, such as _italics_, **bold**, hyperlinks and inline code highlighting, would be useful for comments as well.
