### ISSUE TITLE
Search does not work properly

### ISSUE THREAD

**Issue by okanasik** [ros-infrastructure/answers.ros.org#43]
Search facility does not work properly

For example:
There is a question http://answers.ros.org/question/54165/nao-or-romeo-aldebran-robot-in-v-rep/. When I search with "nao" I want to access every question including "nao" either in title or in answers. However, search returns zero results, but I know that there is a question. Even I search a question with the exact wording of the question, I get lots of irrelevant results and none of them is the exact question I am searching for. Did I miss something?

I can access the above question if I search through google with "nao site:answers.ros.org"

**Comment by tfoote** [comment]
Yeah, i think that the db search requires 4 letters or more to search.  Using google is unfortunately probably the best solution currently.

**Comment by tfoote** [comment]
duplicate #26
