### ISSUE TITLE
Cannot answer questions

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/answers.ros.org#44]
I cannot add an answer or comment, when you click on the links for those, nothing happens.

@tfoote @dirk-thomas @ahendrix

**Comment by tfoote** [comment]
@evgenyfadeev 

I have found a bunch that I cannot click: http://answers.ros.org/question/71920/tf-view_frames-reinstall/ 
But some I can click: http://answers.ros.org/question/71602/pr2-cannot-reset-after-installing-openni_camera/

**Comment by tfoote** [comment]
It seems all questions newer than this one? http://answers.ros.org/question/71863/no-tf-data-received/

currently: 
- http://answers.ros.org/question/71890/can-i-provide-a-null-value-for-a-xacro-macro-parameter/
- http://answers.ros.org/question/71914/non-fully-qualified-frame_id/
- http://answers.ros.org/question/71917/how-do-i-delete-a-rospy-timer/
- http://answers.ros.org/question/71920/tf-view_frames-reinstall/

**Comment by tfoote** [comment]
This seems to be correlated to this report from 3 hours ago that was emailed to me: 

```
Google Login is not working for me. 
This page (http://answers.ros.org/account/signin/) just says

Service unavailable

This service is currently unavailable.

If you have any questions, please contact the site administrator at admin@answers.ros.org
```

**Comment by evgenyfadeev** [comment]
Tully, fixed but not a permanent solution yet - this happened periodically
with another user.
Now looking for a better solution.

On Fri, Aug 9, 2013 at 1:38 AM, Tully Foote notifications@github.comwrote:

> @evgenyfadeev https://github.com/evgenyfadeev
> 
> I have found a bunch that I cannot click:
> http://answers.ros.org/question/71920/tf-view_frames-reinstall/
> But some I can click:
> http://answers.ros.org/question/71602/pr2-cannot-reset-after-installing-openni_camera/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/44#issuecomment-22376267
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
I still can't answer or comment on all the newest questions.

**Comment by evgenyfadeev** [comment]
There is an issue in the compression of javascript files, produces empty js
files, disabled this feature and searching for the reason why this is
happening.

On Fri, Aug 9, 2013 at 1:39 PM, Tully Foote notifications@github.comwrote:

> I still can't answer or comment on all the newest questions.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/44#issuecomment-22411140
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
Closing as the questions are answerable now.
