### ISSUE TITLE
Google and Yahoo OAuth login page report service unavailable

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#45]
You get this back

```
Service unavailable

This service is currently unavailable.

If you have any questions, please contact the site administrator at admin@answers.ros.org
```

**Comment by evgenyfadeev** [comment]
Should be working now, this issue and the other are related.

On Fri, Aug 9, 2013 at 1:12 PM, Tully Foote notifications@github.comwrote:

> You get this back
> 
> Service unavailable
> 
> This service is currently unavailable.
> 
> If you have any questions, please contact the site administrator at admin@answers.ros.org
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/45
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by DLu** [comment]
Confirmed that it seems to be working now. Thanks.
