### ISSUE TITLE
Cannot post to ROS Answers with New Account

### ISSUE THREAD

**Issue by sksellio** [ros-infrastructure/answers.ros.org#47]
I made a new account with an email and password. I then got an email from noreply@answers.ros.org saying that I had to reply to the email without changing the text before I was allowed to post. I hit reply and then send. The email immediately got bounced back to me and I can't post on ROS Answers. I tried adding OpenID to my login methods but this didn't help.

**Comment by evgenyfadeev** [comment]
I have just disabled "allow posting replies by email", because the email receiving server is not running actually.

Do you guys want to be able to make responses by email? Please let me know.
Thank you.

Evgeny.

**Comment by evgenyfadeev** [comment]
@sksellio You should be able to use the site right now, sorry for the confusion with the email responding, we'll need to decide whether to enable posting by email and then enable it properly.

**Comment by sksellio** [comment]
I can post now. Possibly because I removed the password and just use OpenID now. Originally I got an email that said:

"Welcome to ROS Answers!

Important: Please reply to this message, without editing it. We need this to determine your email signature and that the email address is valid and was typed correctly.

Until we receive the response from you, you will not be able ask or answer questions on ROS Answers by email.

Sincerely,
ROS Answers Administrator"

I replied to it and the email just bounced back to me. Not sure why. Is it possible to validate your account through email or do you need OpenID?

**Comment by evgenyfadeev** [comment]
Right - this happened because the "receive email" function for the forum was only halfway enabled - the box was checked for the function, which caused change in the message, but there was no actual function to process those replies on the machine.

Email validation is not required currently on the site, you can just use the site normally now.

**Comment by sksellio** [comment]
Thanks!
