### ISSUE TITLE
"Service unavailable" when posting/editing questions

### ISSUE THREAD

**Issue by georgebrindeiro** [ros-infrastructure/answers.ros.org#48]
For the past couple days I have been getting this error very often:

"Service unavailable

This service is currently unavailable.

If you have any questions, please contact the site administrator at admin@answers.ros.org"

I should also note that admin@answers.ros.org bounces, so maybe you guys could edit the 503 page to redirect people to this page :)

**Comment by tfoote** [comment]
@evgenyfadeev I also cannot login using google getting the same 503 error.

**Comment by evgenyfadeev** [comment]
Disk full. Deleted a large file and improving logrotate.

On Mon, Sep 2, 2013 at 10:27 PM, Tully Foote notifications@github.comwrote:

> @evgenyfadeev https://github.com/evgenyfadeev I also cannot login using
> google getting the same 503 error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/48#issuecomment-23686598
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by georgebrindeiro-vtex** [comment]
If that was the only problem, I'm ok with closing this issue. I would, however, recommend the change in the 503 page so users can actually contact you effectively.

**Comment by evgenyfadeev** [comment]
this was indeed due to the disk fillup

**Comment by skohlbr** [comment]
See also related #50 and #51.
