### ISSUE TITLE
Can't see "Flag offensive" button 

### ISSUE THREAD

**Issue by bit-pirate** [ros-infrastructure/answers.ros.org#49]
Apparently 5 Karma points should be enough to be able flagging, but I can't see the button.

I can't see such a button over at Askbot either, but then they might have a different karma level requirement.

**Comment by mintar** [comment]
I can confirm this; this seems to be a regression. I used to see the button, but now I don't see it any more.

**Comment by dirk-thomas** [comment]
Seems to be visible for multiple people. Closing.

Please comment if it is still an issue.
