### ISSUE TITLE
"Service unavailable" screen provides non-working email address

### ISSUE THREAD

**Issue by skohlbr** [ros-infrastructure/answers.ros.org#51]
Sometimes I get a "service unavailable" screen when using ROS Answers.  Currently always happens when trying to change avatar (see #50) and sometimes when posting a question. The email address stated in that screen (admin@answers.ros.org) does not appear to work for me, as described here: http://answers.ros.org/question/87351/unable-to-change-avatar-image-service-unavailable/
It might be a good idea to provide a link to this issue tracker so people can report problems directly and easily. I for example wasn´t aware of it till Tully mentioned it in his ROS Answers post.

**Comment by tfoote** [comment]
I've updated the 500 error to point to this issue tracker instead of the invalid email.
