### ISSUE TITLE
broken auto links in comments

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#52]
If answers.ros.org auto linkifies a link at the end of a comment it adds a <p> inside the link url. 

```
Please post how to reproduce this otherwise we can't effectively help you. http://wiki.ros.org/Support
```

Links to http://wiki.ros.org/Support<p> if it is at the end of the line.  If you add more words afterwards it works fine. 

@evgenyfadeev

**Comment by tkruse** [comment]
+1 
The issue does not come out well on github, the symptom is that this links to 

```
http://wiki.ros.org/Support</p>
```

not

```
http://wiki.ros.org/Support
```

**Comment by tfoote** [comment]
I verified if I edited the comment for #85 it no longer has the problem when resaved.
