### ISSUE TITLE
broken links in rss feed

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#53]
From forum feedback: 

Hi there, I am using the RSS feed and I've just noticed the following error in the tag which is used as a link at least in feedly: http://answers.ros.org/questions//question/98221/ Even though the tag is correct: http://answers.ros.org/question/98221/amcl-does-not-need-odometry-data/ I hope you can fix this, thanks! Marti

**Comment by evgenyfadeev** [comment]
Fixed this issue, thanks.
