### ISSUE TITLE
users are creating tags with # at the front

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#54]
If one person makes this mistake the tag gets added to the database. Once it's in the database it goes into the suggested tags drop down. And because the # alphabetized earlier people see the #xxx version first and select it instead of xxx. 

I've manually fixed all the tags on answers but they remain in the suggestion drop down. 

Two improvements possible. 
Sort the tag suggestions by their popularity instead of alphabetical. 
Do not display tags with zero usage count.

**Comment by felix-kolbe** [comment]
Asked on Askbot Q&A: http://askbot.org/en/question/11894/prevent-and-fix-tags-starting-with-a-hash-sign/

**Comment by 130s** [comment]
+1 for the explanation. I've been wondering about this since forever.

**Comment by dirk-thomas** [comment]
Could we modify the auto completion list to _not_ show anything which starts with a `#`? @evgenyfadeev Can you give a hint how to achieve that?

**Comment by evgenyfadeev** [comment]
Working on this. I'm thinking maybe add a setting for list of prohibited characters in the beginning of the tag. Old tags hash-prefixed tags will be simply renamed, there is a command "fix_question_tags", I'll add this renaming there.

**Comment by tfoote** [comment]
Can this be intergrated into fix_question_tags.py which takes care of capitalization?

**Comment by evgenyfadeev** [comment]
Yes it will also automatically lowercase the tags.

On Mon, Jan 27, 2014 at 9:08 PM, Tully Foote notifications@github.comwrote:

> Can this be intergrated into fix_question_tags.py which takes care of
> capitalization?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/54#issuecomment-33438443
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
All lowercase will be fine. Would we be able to create a very similar script which simple strips the # signs?

**Comment by evgenyfadeev** [comment]
it will be all in one script, it will fix tags according to the tag
settings.

On Mon, Jan 27, 2014 at 9:50 PM, Tully Foote notifications@github.comwrote:

> All lowercase will be fine. Would we be able to create a very similar
> script which simple strips the # signs?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/54#issuecomment-33440926
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
The tags seem to have disappeared. Can we close this?
