### ISSUE TITLE
rendering error for block quote

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#55]
The content includes a URL and in the code block it is being auto linked: 

http://answers.ros.org/question/83961/problem-with-tf-tutorial/?answer=84996#post-id-84996

**Comment by wjwwood** [comment]
Screenshot:

![screen shot 2013-12-18 at 4 46 58 pm](https://f.cloud.github.com/assets/100427/1779319/328f0d7e-6847-11e3-954e-61aee3c68e42.png)

**Comment by wjwwood** [comment]
Bump. This needs to get fixed, it is very confusing to users.

**Comment by tfoote** [comment]
@evgenyfadeev This is a pretty big problem since you can't copy and paste urls anymore in the block sections.

**Comment by dirk-thomas** [comment]
When "resaving" an existing post this issues seems fixed. Closing.

Please comment if it is still an issue for new posts.
