### ISSUE TITLE
Can't make a question

### ISSUE THREAD

**Issue by DmitryDzz** [ros-infrastructure/answers.ros.org#60]
I can't create a question post. And I've got this message after submit:

Service unavailable
This service is currently unavailable.
Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

Maybe the thing is that I'm new on the service and I have no karma. So I replaced "http:" text with "no-karma-for-links".

My text is:

Wiki has a page (no-karma-for-links wiki. ros. org/action/subscribe/android/Tutorials/hydro/Installation - Android Studio Development Environment?action=subscribe) about creating a new ROS project just in Android Studio. No ros environment is needed. I've tried this method but it doesn't work for me.

My OS is Ubuntu 12.04. Gradle 1.9, Maven 3.1.1, Android Studio 0.4.2.

My steps:

"New Project..." in Android Studio, Minimum required SDK: API 10, Target SDK: API 19, Blank activity.

Sub project's build.gradle with ROS artifacts:

> ```
> apply plugin: 'android'
> 
> android {
>     compileSdkVersion 19
>     buildToolsVersion "19.0.1"
> 
>     defaultConfig {
>         minSdkVersion 10
>         targetSdkVersion 19
>         versionCode 1
>         versionName "1.0"
>     }
>     buildTypes {
>         release {
>             runProguard false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
>         }
>     }
> }
> 
> dependencies {
>     compile 'com.android.support:appcompat-v7:+'
>     compile 'org.ros.android_core:android_gingerbread_mr1:0.1.+'
>     compile 'org.ros.android_core:android_honeycomb_mr2:0.1.+'
>     compile 'org.ros.rosjava_core:rosjava:0.1.+'
> }
> 
> repositories {
>     maven {
>         url 'no-karma-for-links github.com/rosjava/rosjava_mvn_repo/raw/master'
>     }
>     mavenCentral()
> }
> ```

Then I tried to rebuild the project and I got 2 errors:

> ```
> Error: Main manifest has uses-sdk android:minSdkVersion='10' but library uses minSdkVersion='13'
> Error: Execution failed for task ':RoboHead:processDebugManifest'.
> Manifest merging failed. See console for more info.
> ```

Here is my Gradle Console output:

> ```
> Relying on packaging to define the extension of the main artifact has been deprecated and is scheduled to be removed in Gradle 2.0
> :RoboHead:clean
> :RoboHead:compileDebugNdk
> :RoboHead:preBuild UP-TO-DATE
> :RoboHead:preDebugBuild UP-TO-DATE
> :RoboHead:preReleaseBuild UP-TO-DATE
> :RoboHead:prepareComAndroidSupportAppcompatV71901Library
> :RoboHead:prepareOrgRosAndroid_coreAndroid_gingerbread_mr1012Library
> :RoboHead:prepareOrgRosAndroid_coreAndroid_honeycomb_mr2012Library
> :RoboHead:prepareDebugDependencies
> :RoboHead:compileDebugAidl
> :RoboHead:compileDebugRenderscript
> :RoboHead:generateDebugBuildConfig
> :RoboHead:mergeDebugAssets
> :RoboHead:mergeDebugResources
> :RoboHead:processDebugManifest[/home/dmitrydzz/dev/mitya/android2/RoboHead/src/main/AndroidManifest.xml, /tmp/manifestMerge8330386536922274307.xml:2] Main manifest has uses-sdk android:minSdkVersion='10' but library uses minSdkVersion='13'
>  FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':RoboHead:processDebugManifest'.
> Manifest merging failed. See console for more info.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 15.91 secs
> ```

And this is my AndroidManifest.xml:

> ```
> <?xml version="1.0" encoding="utf-8"?>
> <manifest xmlns:android="no-karma-for-links schemas.android.com/apk/res/android"
>     package="ru.robotmitya.robohead" >
> 
>     <application
>         android:allowBackup="true"
>         android:icon="@drawable/ic_launcher"
>         android:label="@string/app_name" >
>         <activity
>             android:name="ru.robotmitya.robohead.MainActivity"
>             android:label="@string/app_name" >
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
> 
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>         </activity>
>     </application>
> 
> </manifest>
> ```

So the question is: what I've missed? I tried to change minimum SDK API and to set it in manifest but it didn't help.

I like the idea to create a ROS Android app in Andrdoid Studio (no catkin, no setup.bash). Is it real or myth?

**Comment by evgenyfadeev** [comment]
Could you try now, please? Thanks.

**Comment by DmitryDzz** [comment]
I tried:

> Service unavailable
> 
> This service is currently unavailable.
> 
> Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

**Comment by ymollard** [comment]
Any change regarding this bug?
I cannot post either.

**Comment by evgenyfadeev** [comment]
I've looked at the memory usage, made a change on the server. Now I will try posting this from your account to reproduce.

**Comment by evgenyfadeev** [comment]
Could you please try now?

**Comment by ymollard** [comment]
Ok test successful, thank you.

**Comment by ymollard** [comment]
Nope, I get this issue again for a new question :D

Here is my question: http://answers.ros.org/question/123366/rviz-and-interactive-markers-why-does-not-pose-automatically-updated/

I could edit an old deleted message to paste this but I cannot create a new thread.

**Comment by evgenyfadeev** [comment]
This is fixed now, sorry for the inconvenience again.

On Wed, Jan 29, 2014 at 1:23 PM, Yoan Mollard notifications@github.comwrote:

> Nope, I get this issue again for a new question :D
> 
> Here is my question:
> http://answers.ros.org/question/123366/rviz-and-interactive-markers-why-does-not-pose-automatically-updated/
> 
> I could edit an old deleted message to paste this but I cannot create a
> new thread.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/60#issuecomment-33600432
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev
