### ISSUE TITLE
Allow new users to link to the ros.org domain

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#61]
Many new users are frustrated by the inability to link to the tutorials they are following, despite instructions in those tutorials specifically requesting that they link to the tutorial when asking for help.

It's understandable that new users should not be allowed to link to arbitrary websites, to prevent spam.

I think users should be allowed to link to a set of whitelisted URLs or domains, so that they can link to the documentation that they're having trouble with. At the very least, this should be a whitelist of the ros.org domains, but could also be expanded to include other whitelisted URLs if we find that users are following off-site documentation.

**Comment by tfoote** [comment]
@evgenyfadeev Is this an option which is available at the moment?

**Comment by evgenyfadeev** [comment]
Tully, working this week on the feature, not available yet.

On Thu, Jan 23, 2014 at 4:07 PM, Tully Foote notifications@github.comwrote:

> @evgenyfadeev https://github.com/evgenyfadeev Is this an option which
> is available at the moment?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/61#issuecomment-33157020
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by trainman419** [comment]
Awesome!

**Comment by trainman419** [comment]
This continues to be a problem for new users: http://answers.ros.org/question/151276/python-problems-installing-ros-on-os-x-109/

**Comment by mikeferguson** [comment]
+1 This would be very useful

I would expand this to be not only ros.org, but github.com as well (that way they can link to specific code they are using).

**Comment by trainman419** [comment]
This continues to be an issue: http://answers.ros.org/question/165726/obstacle_layer-updates-areas-out-of-sight/

**Comment by trainman419** [comment]
Does it make sense to revisit this now that we have more advanced moderation and spam control?

**Comment by tfoote** [comment]
Yes, with the premoderation we can allow full links.

**Comment by gavanderhoorn** [comment]
+1 for this (if my vote was even still necessary :)). Lots of users adding "because I can't post links ..".

**Comment by tfoote** [comment]
with pre moderation links are now allowed for all posts
