### ISSUE TITLE
Unable to post questions

### ISSUE THREAD

**Issue by ubisum** [ros-infrastructure/answers.ros.org#63]
Hi.
Since several days, I can't post questions on ROS Answer's forum.
This is the message I get:

Service unavailable
This service is currently unavailable.
Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

From previous posts in this forum, I see it happened in the past, too.

Is it possible to solve?

Thanks.

**Comment by DmitryDzz** [comment]
This issue duplicates mine #60 with no answer
Seems like nobody home :(

**Comment by evgenyfadeev** [comment]
Closed since it's a duplicate. Could you please comment on #60 whether the issue still persists?
