### ISSUE TITLE
answers.ros.org - "Service unavailable" on "Ask Your Question"

### ISSUE THREAD

**Issue by HWiese1980** [ros-infrastructure/answers.ros.org#64]
Hi folks, just wanted to post a question to answers.ros.org but after clicking on "Ask Your Question" below the input area I get the error message "Service unavailable". 

Any idea what might be wrong?

**Comment by lppier** [comment]
Same here. Probably server down?

**Comment by evgenyfadeev** [comment]
No, sorry. Could you try now, please?

**Comment by lppier** [comment]
Hi yes, it works now, thanks!

Pier.
