### ISSUE TITLE
Code block formatting in preview doesn't agree with rendered result

### ISSUE THREAD

**Issue by jarvisschultz** [ros-infrastructure/answers.ros.org#65]
Here are some recent example questions/answers where this is happening:
[Q1](http://answers.ros.org/question/126356/after-changing-the-buffer-size-error-again-in-publishing-a-array-msgs-with-large-data-length-240in-arduino/)
[Q2](http://answers.ros.org/question/125451/how-to-publish-a-array-msgs-with-large-data-size-in-arduino/)
[Q3](http://answers.ros.org/question/126581/pi_face_tracker-installation-problem/)
[Answer by @x75](http://answers.ros.org/question/9102/how-to-extract-data-from-bag/?answer=125736#post-id-125736)

In all of the links, clicking Edit, and then looking at the preview window, things are rendered correctly.  But on the page linked, things are showing up incorrectly. Example things that are occurring on the linked pages:
- `<` becomes `&lt;`
- `>` becomes `&gt;`
- `#include <std_msgs/Float32MultiArray.h>` gets rendered as `#include <std_msgs float32multiarray.h="">`
- Closing html tags such as `</std_msgs>` are showing up at the bottom of code blocks

**Comment by ahendrix** [comment]
+1; I'm seeing this too. It looks like the rendering engine is trying to interpret and reformat tags that occur within a block that ought to be treated as preformatted text.

See the launch file in this question: http://answers.ros.org/question/126391/nodelet-usage-and-its-role-in-designing-a-complex-controller/

**Comment by evgenyfadeev** [comment]
Fixed, going to close this issue. Please reopen if you see this again.
