### ISSUE TITLE
Can't add the PR2 tag to a question.

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#68]
I'm trying to add the PR2 tag to [this question](http://answers.ros.org/question/128216/opennilaunch-creates-a-different-frames-tree-for-the-kinect/), and whenever I add it to the list of tags and submit, it disappears.

I suspect this is related to recent changes to attempt to force tags to lowercase.

This happens regardless of the case of the tag. I've tried 'PR2' and 'pr2' with the same results.

Interestingly, when trying to add the PR2 tag, it tries to autocomplete to the uppercase version.

This is kind of a big problem for anyone trying to support the PR2, because the PR2 tag is the one that I use to find questions that users have asked pertaining to the PR2.

**Comment by trainman419** [comment]
Still can't add this tag...
Still a problem for PR2 users...

**Comment by tfoote** [comment]
I found that existing questions tagged PR2 still exist:
http://answers.ros.org/questions/scope:unanswered/sort:age-desc/tags:PR2/page:1/but
if you change the caps or try to re add the tag back it is trimmed
away.

**Comment by evgenyfadeev** [comment]
In the settings there is "force lower case tags" selected. For the time being I've unchecked this and applied tag PR2, so this works.

Would you like to lowercase all tags? I'll do that and check the box again. Please let me know.

**Comment by tfoote** [comment]
can we make it force lowercase by turning PR2 into pr2?
