### ISSUE TITLE
Force users to tag questions with their OS and ROS versions

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#69]
The single most commonly-asked initial response that I have to most questions is "what version of ROS and the OS are you running?"

I would like the see the form for submitting a question explicitly ask the user for these; even if they're just converted to tags in the final question. Ideally, they'd just be dropdown menus with all of the expected versions of ROS and Ubuntu (plus other), in newest-first order.

**Comment by tfoote** [comment]
There's a field for required tags. I could list ROS distros at least. The OS is a bit open ended for an enum list.

**Comment by trainman419** [comment]
I'd definitely like to force the ROS version.

For the OS, I think we should force the user to pick one of "Ubuntu 12.04", "Ubuntu 12.10", etc OR "Other OS" which is usually the most meaningful distinction; it helps tell if a user is trying to do an installation from debs or from source. I'm also open to other suggestions on how to elicit this data.

We might want to include some additional common options in the OS list just so we don't make non-ubuntu users feel unwelcome. I'm going to suggest adding "Centos", "Fedora", "Arch", "OSX" and "Gentoo" to that list.

**Comment by evgenyfadeev** [comment]
There is a feature "mandatory tags", however it needs a little work, I will update you when it's ready.

**Comment by gavanderhoorn** [comment]
Bump?

Also related to #110.

**Comment by tfoote** [comment]
I've enabled mandatory tags of at least one rosdistro. it seems to be working. I'm going to close this we can reopen if there's more of an issue. [related discourse discussion](https://discourse.ros.org/t/ros2-support-ros-answers/2620/9?u=tfoote)

For reference I set it to `boxturtle cturtle diamondback electric fuerte groovy hydro indigo jade kinetic lunar melodic ardent` for now.
