### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by simonvpe** [ros-infrastructure/answers.ros.org#71]
I haven't been able to log in since I created my account. Yet, somehow, a question I made got posted to answers.ros.org.

![skrmklipp](https://f.cloud.github.com/assets/717925/2372182/814d3a74-a836-11e3-9716-949f65e2d878.PNG)

**Comment by evgenyfadeev** [comment]
What is your login name on the site?

**Comment by tfoote** [comment]
Closing, no response.
