### ISSUE TITLE
No new notifications

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#73]
I've commented and answered a few questions today, but I don't see any notifications in my answers.ros.org inbox, and I haven't received any emails either.

As an example, I expected notifications about this question, but haven't received them: http://answers.ros.org/question/157886/error-while-loading-nodelet-velocity_multiplexer/

My username on answers.ros.org is `ahendrix`

**Comment by evgenyfadeev** [comment]
I hope this is resolved too. Closing because it's related to the issue with "zero counters" and that one is resolved now. Also I see recent entries in the mail log.

**Comment by 130s** [comment]
I've re-started getting emails. Thanks!
