### ISSUE TITLE
Pageview not accumulating 

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#74]
![answers ros_no_pageviews](https://cloud.githubusercontent.com/assets/1840401/2825299/7be7ac70-cf48-11e3-903a-a9f29f63e1fb.png)

Some questions are already answer-responded with 0 pageview.

**Comment by evgenyfadeev** [comment]
Fixed this issue, thanks.

**Comment by 130s** [comment]
Looks like this is happening again, maybe only for the questions that are opened after some point. 
Just commenting since I don't have a right to re-open here.
