### ISSUE TITLE
Ban the users who are flagged as offensive certain times?

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#75]
e.g. http://answers.ros.org/users/15531/esraa/ keeps posting spam questions over the last 2 hours. I've flagged her/him more than a few times but nothing happens and this person still keeps posting.

**Comment by tfoote** [comment]
They've been blocked. You don't need to open a ticket for that. Just some of the admins need to wake up and check their queue on the site.
