### ISSUE TITLE
answers.ros.org slow/unavailable this morning

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#77]
Thursday, May 8th, 11:45am PST

I've been seeing significant slowness in answers.ros.org for the past hour, and occasionally I get a "Service unavailable" page when trying to load the main page or questions.

**Comment by evgenyfadeev** [comment]
Looks like a DOS, lots of requests come from a couple of IPs.

On Thu, May 8, 2014 at 3:47 PM, Austin notifications@github.com wrote:

> Thursday, May 8th, 11:45am PST
> 
> I've been seeing significant slowness in answers.ros.org for the past
> hour, and occasionally I get a "Service unavailable" page when trying to
> load the main page or questions.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/77
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by evgenyfadeev** [comment]
Enabled a firewall and blocked the two offending IP's. There is no throttling on the requests, so if this repeats either more IPs will need to be blocked or some sort of DOS detection enabled.

**Comment by tfoote** [comment]
Thanks, we've had trouble with this sort of thing on the wiki before with
basically very poorly written scrapers hitting every url.

**Comment by trainman419** [comment]
Is it possible that spam bots are able to post links because the link-posting restriction is enforced on the client side (javascript) instead of the server side?
