### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by hsoltani** [ros-infrastructure/answers.ros.org#80]
Hi
I've got this message:
Service unavailable

This service is currently unavailable.

Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.

What's the problem?

**Comment by prudhvid** [comment]
Same thing happened to me too

**Comment by evgenyfadeev** [comment]
Looking into this issue.

On Sun, Jun 1, 2014 at 8:34 AM, prudhvid notifications@github.com wrote:

> Same thing happened to me
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/80#issuecomment-44775459
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by evgenyfadeev** [comment]
@tfoote migrated database to localhost, there was an issue with the remote one.
