### ISSUE TITLE
Service Unavailable when trying to ask a question

### ISSUE THREAD

**Issue by zcox** [ros-infrastructure/answers.ros.org#81]
On http://answers.ros.org/questions/ask/ after filling in all fields correctly when I click the "Ask Your Question" button at the bottom, I get an error page that says this:

```
Service unavailable

This service is currently unavailable.

Please try back a little bit later. If this continues please look for open issues on https://github.com/ros-infrastructure/answers.ros.org/issues related. If none is found please open a new issue stating how to reproduce this error.
```

**Comment by evgenyfadeev** [comment]
Thank you for reporting about this problem. Could you try again please? Does it work now?

**Comment by zcox** [comment]
Yes it works now, thanks!
