### ISSUE TITLE
sitemap.xml has invalid urls

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#84]
They all point to example.com not answers.ros.org

http://answers.ros.org/sitemap.xml

**Comment by evgenyfadeev** [comment]
Fixed this issue. Also reduced size of sitemap page to speed up the sitemap response.

**Comment by tfoote** [comment]
Thanks for the quick response. Can we keep the full sitemap. Google was fine with the full length before according to the webmaster tools. I'm also tweaking the robots.txt to prevent google from browsing intermediate and search pages.

**Comment by evgenyfadeev** [comment]
I think it's still full, just chunked, but will look into this again.

On Wed, Jul 2, 2014 at 8:14 PM, Tully Foote notifications@github.com
wrote:

> Thanks for the quick response. Can we keep the full sitemap. Google was
> fine with the full length before according to the webmaster tools. I'm also
> tweaking the robots.txt to prevent google from browsing intermediate and
> search pages.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/84#issuecomment-47849111
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
The webmaster tools show many fewer pages just now. It was the number of questions and is now 2000
![sitemap_content](https://cloud.githubusercontent.com/assets/447804/3464225/d2116298-0248-11e4-9092-f9875fa8251f.png)

**Comment by evgenyfadeev** [comment]
Thanks. I think I got it now.

Removed the limit (back to 50k default) and optimized the query a bit
to speed up the map reading.

Takes about 20s to return result, but hopefully it's ok.

On Wed, Jul 2, 2014 at 9:27 PM, Tully Foote notifications@github.com
wrote:

> The webmaster tools show many fewer pages just now. It was the number of
> questions and is now 2000
> [image: sitemap_content]
> https://cloud.githubusercontent.com/assets/447804/3464225/d2116298-0248-11e4-9092-f9875fa8251f.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/84#issuecomment-47853965
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
That's fine. Google's happy with that. They're reporting 17388 web pages which looks right.
