### ISSUE TITLE
<p> and <br> tags in profile description

### ISSUE THREAD

**Issue by mehditlili** [ros-infrastructure/answers.ros.org#86]
I think this is a bug since I see it in almost all profiles that have a description.

**Comment by trainman419** [comment]
I find this annoying as well. I've been mostly ignoring it because the site has bigger problems.

**Comment by georgebrindeiro-vtex** [comment]
Same here. Didn't use to happen... Someone probably tried to escape code within the description, but escaped the enclosing formatting as well.

**Comment by trainman419** [comment]
Matching issue on the main askbot issue tracker: https://github.com/ASKBOT/askbot-devel/issues/274

**Comment by evgenyfadeev** [comment]
Fixed, closing. Please reopen if this issue occurs again.
