### ISSUE TITLE
Cannot mark notifications as read

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#88]
As of a few days ago, I can no longer mark notifications in my inbox on answers.ros.org as read. This means that the notification icon is now permanently stuck RED.

The checkboxes and associated "mark read" buttons no longer exist, and viewing a post that I have notifications about no longer marks it as read either.

**Comment by evgenyfadeev** [comment]
True, I will fix this issue together with the next update of the moderation
queue,
working today the fix will be deployed by Mon.

On Fri, Jul 11, 2014 at 3:32 PM, Austin notifications@github.com wrote:

> As of a few days ago, I can no longer mark notifications in my inbox on
> answers.ros.org as read. This means that the notification icon is now
> permanently stuck RED.
> 
> The checkboxes and associated "mark read" buttons no longer exist, and
> viewing a post that I have notifications about no longer marks it as read
> either.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/88.

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by trainman419** [comment]
I also haven't received any new notifications in my inbox in the past 44 hours, and I have definitely gotten comments on answers and things since then.

**Comment by trainman419** [comment]
This seems to be resolved now.
