### ISSUE TITLE
"Select all" checkbox is gone in Moderation Queue page

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#90]
The page used to allow to choose all. That made things easier when there are more than handful of the list. Now I have to choose 1-by-1 to operate any command on them that takes so longer time.
Seen on FF and Chrome, on Ubuntu Precise and OSX 10.9.

**Comment by NikolausDemmel** [comment]
In particular also for the normal inbox (not the moderation queue), the ability to select and dismiss messages has been gone for a while now, which I find very anoying. @evgenyfadeev mentioned reworking this, but no alternative way of handling these messages has appeared. I question if there really was a need to remove that functionality with no replacement.

**Comment by gavanderhoorn** [comment]
This has been bothering me for some time now as well. While we can 'acknowledge' that we've seen the posts in our inbox, it is no longer possible to clear out the inbox. As @NikolausDemmel wrote this seems to have started when the moderation interface was added / updated.

**Comment by NikolausDemmel** [comment]
@evgenyfadeev can you please comment?

**Comment by evgenyfadeev** [comment]
It can be added again, no problems.
This is useful when you have just a few items on the screen,
but not so when you have many.

On Thu, Aug 7, 2014 at 2:26 PM, Nikolaus Demmel notifications@github.com
wrote:

> @evgenyfadeev https://github.com/evgenyfadeev can you please comment?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/90#issuecomment-51503831
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
This should be resolved by #95 so that if someone else takes action it will clear form your queue. 

And if you block a user, likewise all their entries in the queue will evaporate.
