### ISSUE TITLE
User feedback: cannot answer question.

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#91]
Direct from the user-feedback email, in all it's terribly-formatted glory:

Hello, this is a ROS Answers forum feedback message. Neil Traft (n...@gmail.com, ip:1...) wrote: How do I report a bug in the answers.ros.org website itself? Can I do that here? I'm unable to post an answer to a question. I'm trying to answer: http://answers.ros.org/question/140881/how-can-i-convert-pointcloud2-to-pointcloud/ And this is my answer: Your question is covered in the [PCL Overview](http://wiki.ros.org/pcl/Overview#Converting_between_the_.60sensor_msgs::PointCloud.60_and_.60sensor_msgs::PointCloud2.60_format). In particular, you can either run the [point_cloud_converter](http://wiki.ros.org/point_cloud_converter) node, or you can use [sensor_msgs::convertPointCloud2ToPointCloud](http://www.ros.org/doc/api/sensor_msgs/html/namespacesensor__msgs.html#a56242d12e091c19f7e829bc6b0b0b709). Please help me help someone else. Thank you.

**Comment by trainman419** [comment]
Neil's username is neil-traft: http://answers.ros.org/users/17791/neil-traft/

**Comment by tfoote** [comment]
Is this being blocked because of the link maybe?

**Comment by tfoote** [comment]
We've lowered link requirements to 1 due to our premoderation. I think this should resolve this issue.
