### ISSUE TITLE
No error message when posting self-answer with links and not enough karma

### ISSUE THREAD

**Issue by mrdanbrooks** [ros-infrastructure/answers.ros.org#92]
If you try to post an answer to your own question, and the answer includes a link but you don't have enough karma, nothing happens. The answer doesn't post, and there is no error message telling you what went wrong. 

To reproduce
- Make a new account on answers.ros.org
- Make a question
- Try to post an answer that has a link in it.

**Comment by tfoote** [comment]
link limit moved to 1 karma so everyone can post links now since we've enabled pre-moderation for new users. ( #76 )
