### ISSUE TITLE
Strange duplication of reason in closed questions

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#93]
> Closed for the following reason question is not relevant or outdated by Closed for the following reason "question is not relevant or outdated" by User
> close date 2014-01-01 19:19:19.123456

Seems like a template bug to me?

I get this on all pages with closed questions, doesn't seem to matter for what reason the question was closed.

**Comment by gavanderhoorn** [comment]
Duplicate of ASKBOT/askbot-devel#289.

**Comment by evgenyfadeev** [comment]
Looks like it was fixed? I've tried closing a question and looking at the result.

**Comment by gavanderhoorn** [comment]
I just saw some questions that were recently closed, and things look ok to me now.

Thanks for fixing this. Will older questions' close reasons be updated as well (just curious)?

**Comment by slel** [comment]
Apparently yes, see [comment at ASKBOT/askbot-devel#289](https://github.com/ASKBOT/askbot-devel/issues/289#issuecomment-97719206).
