### ISSUE TITLE
Formatting doesn't seem to work in comments

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/answers.ros.org#94]
This has been bugging me for some time now, but I can't seem to figure out how to use formatting tags in comments (ie: backticks for code etc). Only relevant reference to this I could find is [Why do Comments have a different syntax than Answers?](http://askbot.org/en/question/10091/why-do-comments-have-a-different-syntax-than-answers/) on the AskBot Q&A.

**Comment by tfoote** [comment]
This is a design choice to avoid long comments. Edit your answer or question to add more details. Or if you have enough karma you can extend/correct other answers.

**Comment by gavanderhoorn** [comment]
I guess I can see the rationale behind this, but surely boldface, italic, monospace and url embedding cannot contribute to overly long comments? Those 4 would go a long way to making some comments much easier to read.

**Comment by evgenyfadeev** [comment]
The same formatting as in the Q&A can be used for comments, there is a
config setting for this.
In the future version this will be default.

On Thu, Aug 7, 2014 at 3:28 PM, G.A. vd. Hoorn notifications@github.com
wrote:

> I guess I can see the rationale behind this, but surely boldface, italic,
> monospace and url embedding cannot contribute to overly long comments?
> Those 4 would go a long way to making some comments much easier to read.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/94#issuecomment-51512102
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
I've enabled the markdown syntax in the comments.
