### ISSUE TITLE
inbox "dismissing" messages feature gone

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-infrastructure/answers.ros.org#98]
Over at https://github.com/ros-infrastructure/answers.ros.org/issues/90 as second issue was raised. I'm quoting:

@nikolausdemmel:

> the normal inbox (not the moderation queue), the ability to select and dismiss messages has been gone for a while now, which I find very anoying. @evgenyfadeev mentioned reworking this, but no alternative way of handling these messages has appeared. I question if there really was a need to remove that functionality with no replacement.

@gavanderhoorn:

> This has been bothering me for some time now as well. While we can 'acknowledge' that we've seen the posts in our inbox, it is no longer possible to clear out the inbox. As @NikolausDemmel wrote this seems to have started when the moderation interface was added / updated.

I would vote for simply bringing back the old inbox message selection and dismissal functionality until an alternative is actually implemented. (I personally don't see a need to change it, but that is a maybe a limited view)

**Comment by evgenyfadeev** [comment]
Ok, I will add an [x] button to delete messages.

On Thu, Aug 7, 2014 at 3:54 PM, Nikolaus Demmel notifications@github.com
wrote:

> Over at #90
> https://github.com/ros-infrastructure/answers.ros.org/issues/90 as
> second issue was raised. I'm quoting:
> 
> @nikolausdemmel https://github.com/nikolausdemmel:
> 
> the normal inbox (not the moderation queue), the ability to select and
> dismiss messages has been gone for a while now, which I find very anoying.
> @evgenyfadeev https://github.com/evgenyfadeev mentioned reworking this,
> but no alternative way of handling these messages has appeared. I question
> if there really was a need to remove that functionality with no replacement.
> 
> @gavanderhoorn https://github.com/gavanderhoorn:
> 
> This has been bothering me for some time now as well. While we can
> 'acknowledge' that we've seen the posts in our inbox, it is no longer
> possible to clear out the inbox. As @NikolausDemmel
> https://github.com/NikolausDemmel wrote this seems to have started when
> the moderation interface was added / updated.
> 
> I would vote for simply bringing back the old inbox message selection and
> dismissal functionality until an alternative is actually implemented. (I
> personally don't see a need to change it, but that is a maybe a limited
> view)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-infrastructure/answers.ros.org/issues/98.

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by tfoote** [comment]
Sorry I didn't catch the reference to the normal inbox. I agree having the dismiss all for the normal inbox would be useful. I process a lot of the messages via email and so clearing the inbox is a nice thing to do as I get hundreds to thousands of notifications piling up to the point I never clear them.

**Comment by tfoote** [comment]
"clear new notifications" button added to normal inbox

**Comment by gavanderhoorn** [comment]
Was this ticket also meant to capture the _clear-listing-of-inbox-items-missing_ issue? At least in my interface, that button hasn't returned yet. I do get the _clear notifications_ (or similar), but the messages are never removed from my inbox (the old behaviour). They do loose the _this-is-a-new/updated-msg_ highlighting.

**Comment by tfoote** [comment]
Reopening for delete in addition to remove notifiy

**Comment by gavanderhoorn** [comment]
Friendly bump: last time I checked, I had 417 'items' in my inbox.

**Comment by evgenyfadeev** [comment]
Done.

**Comment by gavanderhoorn** [comment]
@evgenyfadeev: just tested it, inbox is clean. Thanks.

_Select: all_ selects all on the current page. Apparently I had some pages of inbox items to delete.

**Comment by gavanderhoorn** [comment]
Just this morning I noticed that the _select: all | none_ and the _mark seen | delete_ links only worked on items that were not new. Only after visiting a post related to an item in my inbox (and the item lost its yellow (?) colour could I _select: all_ and _delete_.
