### ISSUE TITLE
Differentiate "delete IPs" button

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#99]
Based on @tfoote's suggestion sent out to moderators (cited below), we should be careful for banning IPs. Right now in the moderation queue page, the "delete posts, block and IPs" button is the largest among other functions and thus tempting to hit by mistake. Moreover there's no easy way to judge if the IP should be banned (#97 related?).

> I'd like to suggest that we use the Ban IP only when we see repeated abuse from an IP. With most people on the internet using dynamic IPs and NATs banning an IP can unintentionally hit others and we have zero visibility to help those users who are effected.  

So adding a warning message to the button saying "use with care" might be helpful (but this makes the button even larger). Or locate the button somewhere else to imply that this button needs attention. Just an idea.

**Comment by evgenyfadeev** [comment]
We'll have interface allowing to unblock IPs, hopefully this alleviates the issue.

**Comment by tfoote** [comment]
This is done.
